version: "3.9"
services:
  base-oracle-java21-fp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: base-oracle-jdk-fp:v21

  oracle-java21-setup-server-fp:
    image: base-oracle-jdk-fp:v21
    container_name: base-oracle-jdk-setup-server-fp
    command:
      [
        "sh",
        "-c",
        "chmod +x /temp/scripts/setup.db.paths.sh && /temp/scripts/setup.db.paths.sh  && echo 'removing class files' && rm -rf /temp/src/*.class || true && java --version && sleep 2",
      ]
    volumes:
      - ".:/temp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      base-oracle-java21-fp:
        condition: service_completed_successfully

  postgres-db:
    container_name: postgres-db
    image: postgres
    hostname: postgres-db
    #network_mode: bridge
    restart: always
    env_file: postgres.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./pg-data-init/:/docker-entrypoint-initdb.d/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      oracle-java21-setup-server-fp:
        condition: service_completed_successfully

  oracle-java21-build-server-fp:
    image: base-oracle-jdk-fp:v21
    container_name: base-oracle-jdk-build-server-fp
    command:
      [
        "sh",
        "-c",
        "echo 'removing class files' && rm -rf *.class || true && echo 'list directory' && ls && echo 'get version' && java -version && echo 'compile *.java' && javac -cp java.class.path='/src:/src/lib/postgresql-42.6.0.jar:/src/lib/commons-text-1.11.0.jar:/src/lib/commons-lang3-3.13.0.jar:/src/lib/junit-platform-console-standalone-1.10.1.jar:$CLASSPATH' *.java && echo 'list directory' && ls && sleep 2",
      ]
    volumes:
      - "./src:/src"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres-db:
        condition: service_started

  oracle-java21-finalproj_delay-fp:
    image: base-oracle-jdk-fp:v21
    volumes:
      - "./src:/src"
    command:
      [
        "sh",
        "-c",
        "sleep 5  && echo 'pasuing until start up of databases complete'",
      ]
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      oracle-java21-build-server-fp:
        condition: service_completed_successfully

  oracle-java21-finalproj_all-junit-fp:
    image: base-oracle-jdk-fp:v21
    volumes:
      - "./src:/src"
    command:
      [
        "sh",
        "-c",
        "sleep 5 && echo $POSTGRES_LINK && java -Djava.class.path='/src:/src/lib/postgresql-42.6.0.jar:/src/lib/commons-text-1.11.0.jar:/src/lib/commons-lang3-3.13.0.jar:/src/lib/junit-platform-console-standalone-1.10.1.jar:$CLASSPATH' org.junit.platform.console.ConsoleLauncher execute --scan-class-path",
      ]
    env_file: .env
    environment:
      POSTGRES_LINK: postgres-db
      HOST_NAME: 0.0.0.0
      PORT: 80
      MAX_THREADS: 10
      QUEUE_DEPTH: 25
    ports:
      - "8001:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      oracle-java21-finalproj_delay-fp:
        condition: service_completed_successfully
    links:
      - postgres-db

  oracle-java21-finalproj_all-fp:
    image: base-oracle-jdk-fp:v21
    volumes:
      - "./src:/src"
    command:
      [
        "sh",
        "-c",
        "sleep 5 && echo $POSTGRES_LINK && java -Djava.class.path='/src:/src/lib/postgresql-42.6.0.jar:/src/lib/commons-text-1.11.0.jar:/src/lib/commons-lang3-3.13.0.jar:/src/lib/junit-platform-console-standalone-1.10.1.jar:$CLASSPATH' MainClass",
      ]
    env_file: .env
    environment:
      POSTGRES_LINK: postgres-db
      HOST_NAME: 0.0.0.0
      PORT: 80
      MAX_THREADS: 10
      QUEUE_DEPTH: 25
    ports:
      - "8001:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      oracle-java21-finalproj_all-junit-fp:
        condition: service_completed_successfully
    links:
      - postgres-db
