HttpHelpers Class Reference
The HttpHelpers class provides utility methods for working with HTTP requests and responses.
Static Public Member Functions
static String getPath (String requestUri)
Returns the path component of a given request URI.
static String getQueryString (String requestUri)
Returns the query string from the given request URI.
static Map< String, String > getQueryMap (String query)
Parses a query string and returns a map of key-value pairs.
static String escapeResponseString (String responseString)
Escapes the given response string using the specified text type.
static String escapeResponseString (String responseString, HttpResponseTextType responseType)
Escapes the given response string based on the specified response type.
static Map< String, String > parseCookies (List< String > list)
Parses a list of cookies and returns a map of cookie names to their corresponding values.
static Map< String, String > parseFormData (String formData) throws UnsupportedEncodingException
Parses the given form data and returns a map of key-value pairs.
Private Member Functions
HttpHelpers ()
Static Private Member Functions
static void parseCookies (String cookieString, Map< String, String > cookies)
Parses the cookie string and populates the provided map with the extracted cookies.
Static Private Attributes
static IEnvironment env = Environment.Instance()
The environment instance used by the HttpHelpers class.
Detailed Description
The HttpHelpers class provides utility methods for working with HTTP requests and responses.
Definition at line 14 of file HttpHelpers.java.
Constructor & Destructor Documentation
HttpHelpers()
HttpHelpers.HttpHelpers () [private]
Definition at line 20 of file HttpHelpers.java.
                          {
    }
Member Function Documentation
escapeResponseString() [1/2]
static String HttpHelpers.escapeResponseString (String responseString) [static]
Escapes the given response string using the specified text type.
Parameters
responseString The response string to escape.
Returns
The escaped response string.
Definition at line 74 of file HttpHelpers.java.
                                                                     {
        return escapeResponseString(responseString, HttpResponseTextType.HTML);
    }
References escapeResponseString(), and HttpResponseTextType.HTML.
Referenced by escapeResponseString(), and EchoHandler.handleGetRequest().
escapeResponseString() [2/2]
static String HttpHelpers.escapeResponseString (String responseString, HttpResponseTextType responseType) [static]
Escapes the given response string based on the specified response type.
Parameters
responseString The response string to be escaped.
responseType The type of the response (HTML, JSON, XML, TXT).
Returns
The escaped response string.
Definition at line 85 of file HttpHelpers.java.
                                                                                                        {
        switch (responseType) {
            case HTML:
                return StringEscapeUtils.escapeHtml4(responseString);
            case JSON:
                return StringEscapeUtils.escapeJson(responseString);
            case XML:
                return StringEscapeUtils.escapeXml11(responseString);
            case TXT:
                return responseString;
            default:
                return StringEscapeUtils.escapeHtml4(responseString);
        }
    }
getPath()
static String HttpHelpers.getPath (String requestUri) [static]
Returns the path component of a given request URI.
The path component is the part of the URI before the query string.
Parameters
requestUri the request URI
Returns
the path component of the request URI
Definition at line 30 of file HttpHelpers.java.
                                                    {
        final String[] parts = requestUri.split("\\?");
        return parts[0];
    }
Referenced by HttpRequestContextInfo.HttpRequestContextInfo().
getQueryMap()
static Map< String, String > HttpHelpers.getQueryMap (String query) [static]
Parses a query string and returns a map of key-value pairs.
Parameters
query the query string to parse
Returns
a map containing the key-value pairs from the query string
Definition at line 55 of file HttpHelpers.java.
                                                                {
        final String[] params = query.split("&");
        Map<String, String> map = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        for (String param : params) {
            final String[] parts = param.split("=");
            String name = parts[0];
            String value = parts.length > 1 ? parts[1] : "";
            map.put(name, value);
        }
        return map;
    }
Referenced by HttpRequestContextInfo.HttpRequestContextInfo().
getQueryString()
static String HttpHelpers.getQueryString (String requestUri) [static]
Returns the query string from the given request URI.
Parameters
requestUri the request URI
Returns
the query string
Definition at line 41 of file HttpHelpers.java.
                                                           {
        final String[] parts = requestUri.split("\\?");
        if (parts.length > 1) {
            return parts[1];
        }
        return "";
    }
Referenced by HttpRequestContextInfo.HttpRequestContextInfo().
parseCookies() [1/2]
static Map< String, String > HttpHelpers.parseCookies (List< String > list) [static]
Parses a list of cookies and returns a map of cookie names to their corresponding values.
Parameters
list The list of cookies to be parsed.
Returns
A map of cookie names to their corresponding values.
Definition at line 107 of file HttpHelpers.java.
                                                                      {
        Map<String, String> cookies = new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
        for (String cookie : list) {
            parseCookies(cookie, cookies);
        }
        return cookies;
    }
References parseCookies().
Referenced by HttpRequestContextInfo.HttpRequestContextInfo(), and parseCookies().
parseCookies() [2/2]
static void HttpHelpers.parseCookies (String cookieString, Map< String, String > cookies) [static], [private]
Parses the cookie string and populates the provided map with the extracted cookies.
Parameters
cookieString The string containing the cookies in the format "key1=value1; key2=value2; ..."
cookies The map to store the extracted cookies, where the key is the cookie name and the value is the cookie value.
Definition at line 124 of file HttpHelpers.java.
                                                                                       {
        final String[] cookiePairs = cookieString.split("; ");
        for (String cookiePair : cookiePairs) {
            final String[] cookieValue = cookiePair.split("=");
            String key = cookieValue[0];
            String value = cookieValue.length > 1 ? cookieValue[1] : "";
            cookies.put(key, value);
        }
    }
parseFormData()
static Map< String, String > HttpHelpers.parseFormData (String formData) throws UnsupportedEncodingException [static]
Parses the given form data and returns a map of key-value pairs.
Parameters
formData the form data to be parsed
Returns
a map containing the parsed key-value pairs
Exceptions
UnsupportedEncodingException if the encoding is not supported
Definition at line 141 of file HttpHelpers.java.
                                                                                                         {
        Map<String, String> map = new TreeMap<>();
        final String[] pairs = formData.split("&");
        for (String pair : pairs) {
            final String[] keyValue = pair.split("=");
            String value = URLDecoder.decode(keyValue[1], "UTF-8");
            map.put(keyValue[0], value);
        }
        return map;
    }
Referenced by BaseRouteHandler.parseFormData().
Member Data Documentation
env
IEnvironment HttpHelpers.env = Environment.Instance() [static], [private]
The environment instance used by the HttpHelpers class.
Definition at line 18 of file HttpHelpers.java.
The documentation for this class was generated from the following file:
HttpHelpers.java