UserInteraction Class Reference
The UserInteraction class provides methods for interacting with the user through the console.
Public Member Functions
UserInteraction ()
This class represents the user interaction functionality of the program.
Static Public Member Functions
static void sendPrompt (String prompt)
Prints the given prompt to the console and flushes the output stream.
static void sendPrompt (String[] prompt)
Prints the given prompt to the console and flushes the output stream.
static String getConsoleInputString ()
Reads a line of text from the console input and returns it as a string.
static Boolean getConsoleInputBoolean ()
Reads a boolean value from the console input.
static Integer getConsoleInputInteger ()
Reads an integer value from the console input.
static Double getConsoleInputDouble ()
Reads a double value from the console input.
static String getInput (String prompt)
Prompts the user for input and returns the input as a String.
static Boolean getInputBoolean (String prompt)
Prompts the user for a boolean input using the given prompt message.
static Integer getInputInteger (String prompt)
Prompts the user for an input and returns the input as an Integer.
static Double getInputDouble (String prompt)
Prompts the user for input and returns the input as a Double.
Static Package Functions
[static initializer]
The output stream used for writing to the console.
Static Private Attributes
static AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The function returns an instance of the AppLoggingAgent class.
static Scanner consoleIn = null
Scanner object used to read input from the console.
Detailed Description
The UserInteraction class provides methods for interacting with the user through the console.
Definition at line 7 of file UserInteraction.java.
Constructor & Destructor Documentation
UserInteraction()
UserInteraction.UserInteraction ()
This class represents the user interaction functionality of the program.
Definition at line 35 of file UserInteraction.java.
                             {
    }
Member Function Documentation
[static initializer]()
UserInteraction.[static initializer] [static], [package]
The output stream used for writing to the console.
Initializes the console input and output streams.
References consoleIn.
getConsoleInputBoolean()
static Boolean UserInteraction.getConsoleInputBoolean () [static]
Reads a boolean value from the console input.
Returns
the boolean value read from the console input
Definition at line 78 of file UserInteraction.java.
                                                   {
        return consoleIn.nextBoolean();
    }
References consoleIn.
getConsoleInputDouble()
static Double UserInteraction.getConsoleInputDouble () [static]
Reads a double value from the console input.
Returns
the double value read from the console input.
Definition at line 96 of file UserInteraction.java.
                                                 {
        return consoleIn.nextDouble();
    }
References consoleIn.
getConsoleInputInteger()
static Integer UserInteraction.getConsoleInputInteger () [static]
Reads an integer value from the console input.
Returns
the integer value read from the console input
Definition at line 87 of file UserInteraction.java.
                                                   {
        return consoleIn.nextInt();
    }
References consoleIn.
getConsoleInputString()
static String UserInteraction.getConsoleInputString () [static]
Reads a line of text from the console input and returns it as a string.
Returns
the line of text entered by the user
Definition at line 69 of file UserInteraction.java.
                                                 {
        return consoleIn.nextLine();
    }
References consoleIn.
Referenced by getInput().
getInput()
static String UserInteraction.getInput (String prompt) [static]
Prompts the user for input and returns the input as a String.
Parameters
prompt the message to display to the user as a prompt
Returns
the user's input as a String
Definition at line 106 of file UserInteraction.java.
                                                 {
        sendPrompt(prompt);
        String nextString = getConsoleInputString();
        sendPrompt(" >> " + nextString);
        return nextString;
    }
References getConsoleInputString(), and sendPrompt().
Referenced by getInputBoolean(), getInputDouble(), and getInputInteger().
getInputBoolean()
static Boolean UserInteraction.getInputBoolean (String prompt) [static]
Prompts the user for a boolean input using the given prompt message.
Parameters
prompt the message to display to the user as a prompt
Returns
the boolean value entered by the user
Definition at line 119 of file UserInteraction.java.
                                                         {
        String value = getInput(prompt);
        if (value.toLowerCase().startsWith("y")) {
            return true;
        }
        if (value.toLowerCase().startsWith("n")) {
            return false;
        }
        Boolean nextBoolean = Boolean.valueOf(value);
        return nextBoolean;
    }
References getInput().
getInputDouble()
static Double UserInteraction.getInputDouble (String prompt) [static]
Prompts the user for input and returns the input as a Double.
Parameters
prompt the message to display to the user as a prompt
Returns
the user's input as a Double
Definition at line 148 of file UserInteraction.java.
                                                       {
        Double nextDouble = Double.valueOf(getInput(prompt));
        return nextDouble;
    }
References getInput().
getInputInteger()
static Integer UserInteraction.getInputInteger (String prompt) [static]
Prompts the user for an input and returns the input as an Integer.
Parameters
prompt the message to display to the user as a prompt
Returns
the user's input as an Integer
Definition at line 137 of file UserInteraction.java.
                                                         {
        Integer nextInt = Integer.valueOf(getInput(prompt));
        return nextInt;
    }
References getInput().
sendPrompt() [1/2]
static void UserInteraction.sendPrompt (String prompt) [static]
Prints the given prompt to the console and flushes the output stream.
Parameters
prompt the prompt to be printed to the console
Definition at line 43 of file UserInteraction.java.
                                                 {
        //// print the given prompt to the console
        // consoleOut.println(prompt);
        //// flush the output stream
        // consoleOut.flush();
        logging.log(prompt);
    }
References logging.
Referenced by getInput().
sendPrompt() [2/2]
static void UserInteraction.sendPrompt (String[] prompt) [static]
Prints the given prompt to the console and flushes the output stream.
Parameters
prompt the prompt to be printed to the console
Definition at line 56 of file UserInteraction.java.
                                                   {
        //// print the given prompt to the console
        // consoleOut.println(prompt);
        //// flush the output stream
        // consoleOut.flush();
        logging.log(prompt);
    }
References logging.
Member Data Documentation
consoleIn
Scanner UserInteraction.consoleIn = null [static], [private]
Scanner object used to read input from the console.
Definition at line 18 of file UserInteraction.java.
Referenced by [static initializer](), getConsoleInputBoolean(), getConsoleInputDouble(), getConsoleInputInteger(), and getConsoleInputString().
logging
AppLoggingAgent UserInteraction.logging = new AppLoggingAgent(new AppLoggingStream()) [static], [private]
The function returns an instance of the AppLoggingAgent class.
Returns
The method is returning an instance of the AppLoggingAgent class.
Definition at line 13 of file UserInteraction.java.
Referenced by sendPrompt(), and sendPrompt().
The documentation for this class was generated from the following file:
UserInteraction.java