BaseShoppingSystemHandler Class Reference
Public Member Functions
BaseShoppingSystemHandler (ShoppingBusinessLayerService shoppingBusinessService)
Constructs a BaseShoppingSystemHandler object with the specified shopping business layer service.
void handle (HttpExchange httpExchange) throws IOException
Handles the HTTP request by processing the given HttpExchange object.
Public Member Functions inherited from BaseRouteHandler
String buildResponse (String responseString, HttpResponseTextType responseType)
Builds a response string based on the given response string and response type.
Protected Member Functions
ShoppingBusinessLayerService getShoppingBusinessService ()
abstract String handleGetRequest (HttpExchange httpExchange)
Handles the GET request and returns a response as a String.
abstract String handlePostRequest (HttpExchange httpExchange)
Handles the POST request and returns a string response.
Protected Member Functions inherited from BaseRouteHandler
String buildResponse (String responseString)
Builds a response string.
void handleResponse (HttpExchange httpExchange, String responseString, Integer responseCode) throws IOException
Handles the HTTP response by sending the specified response string and response code.
void handleResponse (HttpExchange httpExchange, HttpResponseTextType responseType, String responseString, Integer responseCode) throws IOException
Handles the HTTP response by setting the response content type, sending the response headers, and writing the response string to the output stream.
void setResponseContentType (HttpExchange httpExchange)
Sets the response content type for the given HttpExchange object.
void setResponseContentType (HttpExchange httpExchange, HttpResponseTextType responseType)
Sets the response content type based on the specified HttpResponseTextType.
IHttpRequestContextInfo processUri (HttpExchange httpExchange)
Processes the URI of the HTTP request and returns an instance of IHttpRequestContextInfo.
void addCookie (HttpExchange httpExchange, IHttpCookie cookie)
Adds a cookie to the response headers of the given HttpExchange.
Private Member Functions
String handleMethodRequest (HttpExchange httpExchange, final String method) throws Exception
Handles the method request based on the HTTP method.
Private Attributes
ShoppingBusinessLayerService shoppingBusinessService
The service responsible for handling the business logic of the shopping system.
Additional Inherited Members
Static Protected Member Functions inherited from BaseRouteHandler
static Map< String, String > parseFormData (String formData) throws UnsupportedEncodingException
Parses the given form data and returns a map of key-value pairs.
Protected Attributes inherited from BaseRouteHandler
AppLoggingAgent logger = new AppLoggingAgent(new AppLoggingStream())
Detailed Description
Definition at line 6 of file BaseShoppingSystemHandler.java.
Constructor & Destructor Documentation
BaseShoppingSystemHandler()
BaseShoppingSystemHandler.BaseShoppingSystemHandler (ShoppingBusinessLayerService shoppingBusinessService)
Constructs a BaseShoppingSystemHandler object with the specified shopping business layer service.
Parameters
shoppingBusinessService The shopping business layer service.
Definition at line 19 of file BaseShoppingSystemHandler.java.
                                                                                           {
        this.shoppingBusinessService = shoppingBusinessService;
    }
References shoppingBusinessService.
Member Function Documentation
getShoppingBusinessService()
ShoppingBusinessLayerService BaseShoppingSystemHandler.getShoppingBusinessService () [protected]
Returns
the shoppingBusinessService
Definition at line 74 of file BaseShoppingSystemHandler.java.
                                                                        {
        return shoppingBusinessService;
    };
References shoppingBusinessService.
handle()
void BaseShoppingSystemHandler.handle (HttpExchange httpExchange) throws IOException
Handles the HTTP request by processing the given HttpExchange object.
This method is responsible for logging the request details, handling the request method, building the response, and handling any exceptions that may occur.
Parameters
httpExchange The HttpExchange object representing the HTTP request.
Exceptions
IOException If an I/O error occurs while handling the request.
Definition at line 32 of file BaseShoppingSystemHandler.java.
                                                                     {
        String buildResponse = "";
        int responseCode = 500;
        logger.log("httpExchange: " + httpExchange.getRequestMethod() + " " + httpExchange.getRequestURI());
        try {
            final String method = httpExchange.getRequestMethod().toString().toUpperCase();
            String requestParamValue = handleMethodRequest(httpExchange, method);
            buildResponse = buildResponse(requestParamValue);
            logger.log("Response: " + buildResponse);
        } catch (Exception e) {
            logger.log("Error handling request", e);
            buildResponse = buildResponse(e.getMessage());
            responseCode = 500;
        }
        this.handleResponse(httpExchange, buildResponse, responseCode);
    }
References BaseRouteHandler.buildResponse(), handleMethodRequest(), BaseRouteHandler.handleResponse(), AppLoggingAgent.log(), and BaseRouteHandler.logger.
handleGetRequest()
abstract String BaseShoppingSystemHandler.handleGetRequest (HttpExchange httpExchange) [abstract], [protected]
Handles the GET request and returns a response as a String.
Parameters
httpExchange the HTTP exchange object representing the request and response
Returns
a String representing the response to the GET request
Referenced by handleMethodRequest().
handleMethodRequest()
String BaseShoppingSystemHandler.handleMethodRequest (HttpExchange httpExchange, final String method) throws Exception [private]
Handles the method request based on the HTTP method.
Parameters
httpExchange The HTTP exchange object.
method The HTTP method.
Returns
The response string.
Exceptions
Exception If an unsupported HTTP method is provided.
Definition at line 60 of file BaseShoppingSystemHandler.java.
                                                                                                        {
        switch (method) {
            case "GET":
                return handleGetRequest(httpExchange);
            case "POST":
                return handlePostRequest(httpExchange);
            default:
                throw new Exception("Unsupported HTTP method: " + method);
        }
    }
References handleGetRequest(), and handlePostRequest().
Referenced by handle().
handlePostRequest()
abstract String BaseShoppingSystemHandler.handlePostRequest (HttpExchange httpExchange) [abstract], [protected]
Handles the POST request and returns a string response.
Parameters
httpExchange the HTTP exchange object
Returns
the string response
Referenced by handleMethodRequest().
Member Data Documentation
shoppingBusinessService
ShoppingBusinessLayerService BaseShoppingSystemHandler.shoppingBusinessService [private]
The service responsible for handling the business logic of the shopping system.
Definition at line 11 of file BaseShoppingSystemHandler.java.
Referenced by BaseShoppingSystemHandler(), and getShoppingBusinessService().
The documentation for this class was generated from the following file:
BaseShoppingSystemHandler.java