ProductDTOHome Class Reference
This class represents a home for ProductDTO objects.
Public Member Functions
IDTO newDTOInstance ()
Creates a new instance of ProductDTO.
Public Member Functions inherited from BaseDTOHome
List< IDTO > queryDTOs (IDTO dtoQuery)
Queries the database for a list of DTOs based on the provided query DTO.
Boolean saveDTO (IDTO dto)
Saves a single DTO object.
Boolean saveDTOs (List< IDTO > dtos)
Saves a list of DTOs.
IDbResultProcessor getLoadProcessor ()
Gets the result processor for loading data from the database.
String getLoadSql (IDTO dto)
Returns the SQL query for loading data from the database based on the provided DTO object.
IDbResultProcessor getSaveProcessor (IDTO dto)
The function returns an instance of a class that implements the IDbResultProcessor interface, which processes the result set from a database save operation and returns a list of DTO objects.
String getSaveSql (IDTO dto)
Returns the SQL statement for saving the given DTO.
Static Public Member Functions
static IDTOHome Instance ()
Returns the singleton instance of ProductDTOHome.
Private Member Functions
ProductDTOHome ()
Static Private Attributes
static ProductDTOHome instance = new ProductDTOHome()
Additional Inherited Members
Protected Member Functions inherited from BaseDTOHome
Boolean processLoadResult (ResultSet rs, List< IDTO > results) throws SQLException
Processes the load result from a ResultSet and populates a list of DTO objects.
Boolean processLoadResult (ResultSet rs, IDTO dto) throws SQLException
Processes the load result from a ResultSet and sets the values in the given DTO.
Object getValueFromResultSet (ResultSet rs, String fieldName, DTOTypes dtoTypes) throws SQLException
Retrieves the value from the ResultSet based on the field name and data type.
String formatValueForQuery (Object value, DTOTypes dtoTypes)
Formats the given value for query based on the specified DTO type.
Boolean processSaveResult (ResultSet rs, IDTO dto, List< IDTO > saveResults) throws SQLException
Processes the save result from the database and updates the DTO object accordingly.
void buildInsertSql (StringBuilder sb, IDTO dto)
Builds the SQL query for inserting data into the database table.
void buildUpdateSql (StringBuilder sb, IDTO dto)
Builds an SQL update statement for the given DTO object.
Detailed Description
This class represents a home for ProductDTO objects.
It extends the BaseDTOHome class and implements the IDTOHome interface.
Definition at line 6 of file ProductDTOHome.java.
Constructor & Destructor Documentation
ProductDTOHome()
ProductDTOHome.ProductDTOHome () [private]
Definition at line 10 of file ProductDTOHome.java.
                             {
    }
Member Function Documentation
Instance()
static IDTOHome ProductDTOHome.Instance () [static]
Returns the singleton instance of ProductDTOHome.
Returns
the singleton instance of ProductDTOHome
Definition at line 18 of file ProductDTOHome.java.
                                      {
        return instance;
    }
References instance.
Referenced by ProductDTO.getDtoHome(), ShoppingBusinessLayerService.getProductById(), ShoppingBusinessLayerService.getProductCatalog(), TestDTO.testCartItemDTO_1(), TestDTO.testCartItemDTO_2(), TestDTO.testOrderItemDTO_1(), TestDTO.testProductDTO_1(), TestDTO.testProductDTO_2(), TestDTO.testProductDTO_3(), and TestDTO.testProductDTO_4().
newDTOInstance()
IDTO ProductDTOHome.newDTOInstance ()
Creates a new instance of ProductDTO.
Returns
a new instance of ProductDTO
Reimplemented from BaseDTOHome.
Definition at line 27 of file ProductDTOHome.java.
                                 {
        return new ProductDTO();
    }
Member Data Documentation
instance
ProductDTOHome ProductDTOHome.instance = new ProductDTOHome() [static], [private]
Definition at line 8 of file ProductDTOHome.java.
Referenced by Instance().
The documentation for this class was generated from the following file:
ProductDTOHome.java