PurchaseDTOHome Class Reference
The PurchaseDTOHome class represents a home for PurchaseDTO objects.
Public Member Functions
IDTO newDTOInstance ()
Creates a new instance of PurchaseDTO.
Public Member Functions inherited from BaseDTOHome
List< IDTO > queryDTOs (IDTO dtoQuery)
Queries the database for a list of DTOs based on the provided query DTO.
Boolean saveDTO (IDTO dto)
Saves a single DTO object.
Boolean saveDTOs (List< IDTO > dtos)
Saves a list of DTOs.
IDbResultProcessor getLoadProcessor ()
Gets the result processor for loading data from the database.
String getLoadSql (IDTO dto)
Returns the SQL query for loading data from the database based on the provided DTO object.
IDbResultProcessor getSaveProcessor (IDTO dto)
The function returns an instance of a class that implements the IDbResultProcessor interface, which processes the result set from a database save operation and returns a list of DTO objects.
String getSaveSql (IDTO dto)
Returns the SQL statement for saving the given DTO.
Static Public Member Functions
static IDTOHome Instance ()
Returns the singleton instance of PurchaseDTOHome.
Private Member Functions
PurchaseDTOHome ()
Static Private Attributes
static PurchaseDTOHome instance = new PurchaseDTOHome()
Additional Inherited Members
Protected Member Functions inherited from BaseDTOHome
Boolean processLoadResult (ResultSet rs, List< IDTO > results) throws SQLException
Processes the load result from a ResultSet and populates a list of DTO objects.
Boolean processLoadResult (ResultSet rs, IDTO dto) throws SQLException
Processes the load result from a ResultSet and sets the values in the given DTO.
Object getValueFromResultSet (ResultSet rs, String fieldName, DTOTypes dtoTypes) throws SQLException
Retrieves the value from the ResultSet based on the field name and data type.
String formatValueForQuery (Object value, DTOTypes dtoTypes)
Formats the given value for query based on the specified DTO type.
Boolean processSaveResult (ResultSet rs, IDTO dto, List< IDTO > saveResults) throws SQLException
Processes the save result from the database and updates the DTO object accordingly.
void buildInsertSql (StringBuilder sb, IDTO dto)
Builds the SQL query for inserting data into the database table.
void buildUpdateSql (StringBuilder sb, IDTO dto)
Builds an SQL update statement for the given DTO object.
Detailed Description
The PurchaseDTOHome class represents a home for PurchaseDTO objects.
It extends the BaseDTOHome class and implements the IDTOHome interface. This class provides methods for creating new instances of PurchaseDTO objects.
Definition at line 7 of file PurchaseDTOHome.java.
Constructor & Destructor Documentation
PurchaseDTOHome()
PurchaseDTOHome.PurchaseDTOHome () [private]
Definition at line 11 of file PurchaseDTOHome.java.
                              {
    }
Member Function Documentation
Instance()
static IDTOHome PurchaseDTOHome.Instance () [static]
Returns the singleton instance of PurchaseDTOHome.
Returns
the singleton instance of PurchaseDTOHome
Definition at line 19 of file PurchaseDTOHome.java.
                                      {
        return instance;
    }
References instance.
Referenced by PurchaseDTO.getDtoHome(), ShoppingPaymentService.processPayment(), TestDTO.testOrderDTO_1(), TestDTO.testOrderDTO_2(), TestDTO.testOrderItemDTO_1(), TestDTO.testPurchaseDTO_1(), and TestDTO.testPurchaseDTO_2().
newDTOInstance()
IDTO PurchaseDTOHome.newDTOInstance ()
Creates a new instance of PurchaseDTO.
Returns
a new instance of PurchaseDTO
Reimplemented from BaseDTOHome.
Definition at line 28 of file PurchaseDTOHome.java.
                                 {
        return new PurchaseDTO();
    }
Member Data Documentation
instance
PurchaseDTOHome PurchaseDTOHome.instance = new PurchaseDTOHome() [static], [private]
Definition at line 9 of file PurchaseDTOHome.java.
Referenced by Instance().
The documentation for this class was generated from the following file:
PurchaseDTOHome.java