BaseRouteHandler Class Reference
Public Member Functions
String buildResponse (String responseString, HttpResponseTextType responseType)
Builds a response string based on the given response string and response type.
Protected Member Functions
String buildResponse (String responseString)
Builds a response string.
void handleResponse (HttpExchange httpExchange, String responseString, Integer responseCode) throws IOException
Handles the HTTP response by sending the specified response string and response code.
void handleResponse (HttpExchange httpExchange, HttpResponseTextType responseType, String responseString, Integer responseCode) throws IOException
Handles the HTTP response by setting the response content type, sending the response headers, and writing the response string to the output stream.
void setResponseContentType (HttpExchange httpExchange)
Sets the response content type for the given HttpExchange object.
void setResponseContentType (HttpExchange httpExchange, HttpResponseTextType responseType)
Sets the response content type based on the specified HttpResponseTextType.
IHttpRequestContextInfo processUri (HttpExchange httpExchange)
Processes the URI of the HTTP request and returns an instance of IHttpRequestContextInfo.
void addCookie (HttpExchange httpExchange, IHttpCookie cookie)
Adds a cookie to the response headers of the given HttpExchange.
Static Protected Member Functions
static Map< String, String > parseFormData (String formData) throws UnsupportedEncodingException
Parses the given form data and returns a map of key-value pairs.
Protected Attributes
AppLoggingAgent logger = new AppLoggingAgent(new AppLoggingStream())
Detailed Description
Definition at line 9 of file BaseRouteHandler.java.
Member Function Documentation
addCookie()
void BaseRouteHandler.addCookie (HttpExchange httpExchange, IHttpCookie cookie) [protected]
Adds a cookie to the response headers of the given HttpExchange.
Parameters
httpExchange The HttpExchange object representing the HTTP request and response.
cookie The IHttpCookie object representing the cookie to be added.
Definition at line 142 of file BaseRouteHandler.java.
                                                                            {
        Headers respHeaders = httpExchange.getResponseHeaders();
        respHeaders.add("Set-Cookie", cookie.toString());
    }
References IHttpCookie.toString().
buildResponse() [1/2]
String BaseRouteHandler.buildResponse (String responseString) [protected]
Builds a response string.
Parameters
responseString The response string to be built.
Returns
The built response string.
Definition at line 49 of file BaseRouteHandler.java.
                                                          {
        return buildResponse(responseString, HttpResponseTextType.HTML);
    }
References buildResponse(), and HttpResponseTextType.HTML.
buildResponse() [2/2]
String BaseRouteHandler.buildResponse (String responseString, HttpResponseTextType responseType)
Builds a response string based on the given response string and response type.
If the response type is JSON, TXT, or XML, the response string is appended as is. Otherwise, the response string is wrapped in HTML tags.
Parameters
responseString The response string to be included in the response.
responseType The type of the response (JSON, TXT, XML, etc.).
Returns
The built response string.
Implements IHttpRouteHandler.
Definition at line 23 of file BaseRouteHandler.java.
                                                                                          {
        StringBuilder responseBuilder = new StringBuilder();
        switch (responseType) {
            case JSON:
            case TXT:
            case XML:
                responseBuilder.append(responseString);
                break;
            default:
                responseBuilder.append("<html>").append("<body>")
                        .append(responseString)
                        .append("</body>")
                        .append("</html>");
                break;
        }
        String responseBuilderString = responseBuilder.toString();
        logger.log("[BaseRouteHandler] Response: " + responseBuilderString);
        return responseBuilderString;
    }
References AppLoggingAgent.log(), and logger.
Referenced by buildResponse(), BaseShoppingSystemHandler.handle(), and EchoHandler.handle().
handleResponse() [1/2]
void BaseRouteHandler.handleResponse (HttpExchange httpExchange, HttpResponseTextType responseType, String responseString, Integer responseCode) throws IOException [protected]
Handles the HTTP response by setting the response content type, sending the response headers, and writing the response string to the output stream.
Parameters
httpExchange The HTTP exchange object.
responseType The type of the response text.
responseString The response string to be sent.
responseCode The HTTP response code.
Exceptions
IOException If an I/O error occurs while handling the response.
Definition at line 77 of file BaseRouteHandler.java.
                               {
        setResponseContentType(httpExchange, responseType);
        try (OutputStream outputStream = httpExchange.getResponseBody()) {
            httpExchange.sendResponseHeaders(responseCode, responseString.length());
            outputStream.write(responseString.getBytes());
            outputStream.flush();
        } catch (IOException e) {
            logger.log("Error handling response", e);
            throw e;
        }
    }
References AppLoggingAgent.log(), logger, and setResponseContentType().
handleResponse() [2/2]
void BaseRouteHandler.handleResponse (HttpExchange httpExchange, String responseString, Integer responseCode) throws IOException [protected]
Handles the HTTP response by sending the specified response string and response code.
This method is used internally by the class and should not be called directly.
Parameters
httpExchange The HttpExchange object representing the HTTP request and response.
responseString The string to be sent as the response body.
responseCode The HTTP response code to be sent.
Exceptions
IOException If an I/O error occurs while sending the response.
Definition at line 62 of file BaseRouteHandler.java.
                               {
        handleResponse(httpExchange, HttpResponseTextType.HTML, responseString, responseCode);
    }
References handleResponse(), and HttpResponseTextType.HTML.
Referenced by BaseShoppingSystemHandler.handle(), EchoHandler.handle(), and handleResponse().
parseFormData()
static Map< String, String > BaseRouteHandler.parseFormData (String formData) throws UnsupportedEncodingException [static], [protected]
Parses the given form data and returns a map of key-value pairs.
Parameters
formData the form data to be parsed
Returns
a map containing the parsed key-value pairs
Exceptions
UnsupportedEncodingException if the encoding is not supported
Definition at line 154 of file BaseRouteHandler.java.
                                                                                                            {
        return HttpHelpers.parseFormData(formData);
    }
References HttpHelpers.parseFormData().
processUri()
IHttpRequestContextInfo BaseRouteHandler.processUri (HttpExchange httpExchange) [protected]
Processes the URI of the HTTP request and returns an instance of IHttpRequestContextInfo.
Parameters
httpExchange The HttpExchange object representing the HTTP request.
Returns
An instance of IHttpRequestContextInfo containing information about the HTTP request.
Definition at line 132 of file BaseRouteHandler.java.
                                                                            {
        return new HttpRequestContextInfo(httpExchange);
    }
setResponseContentType() [1/2]
void BaseRouteHandler.setResponseContentType (HttpExchange httpExchange) [protected]
Sets the response content type for the given HttpExchange object.
The content type is set to HttpResponseTextType.HTML by default.
Parameters
httpExchange The HttpExchange object for which to set the response content type.
Definition at line 98 of file BaseRouteHandler.java.
                                                                     {
        setResponseContentType(httpExchange, HttpResponseTextType.HTML);
    }
References HttpResponseTextType.HTML, and setResponseContentType().
Referenced by handleResponse(), and setResponseContentType().
setResponseContentType() [2/2]
void BaseRouteHandler.setResponseContentType (HttpExchange httpExchange, HttpResponseTextType responseType) [protected]
Sets the response content type based on the specified HttpResponseTextType.
Parameters
httpExchange The HttpExchange object representing the HTTP request and response.
responseType The HttpResponseTextType indicating the desired response content type.
Definition at line 108 of file BaseRouteHandler.java.
                                                                                                        {
        Headers h = httpExchange.getResponseHeaders();
        switch (responseType) {
            case JSON:
                h.set("Content-Type", "application/json");
                break;
            case XML:
                h.set("Content-Type", "application/xml");
                break;
            case TXT:
                h.set("Content-Type", "text/plain");
                break;
            default:
                h.set("Content-Type", "text/html");
                break;
        }
    }
Member Data Documentation
logger
AppLoggingAgent BaseRouteHandler.logger = new AppLoggingAgent(new AppLoggingStream()) [protected]
Definition at line 11 of file BaseRouteHandler.java.
Referenced by buildResponse(), BaseShoppingSystemHandler.handle(), EchoHandler.handle(), and handleResponse().
The documentation for this class was generated from the following file:
BaseRouteHandler.java