WebServer Class Reference
The WebServer class represents a web server that listens for HTTP requests and handles them accordingly.
Public Member Functions
WebServer ()
void start ()
Starts the web server.
HttpContext addRoute (String route, HttpHandler handler)
Adds a route to the web server.
HttpContext addRoute (String route, HttpHandler handler, com.sun.net.httpserver.Authenticator authenticator)
Adds a route to the web server with the specified route path, handler, and authenticator.
Static Public Member Functions
static void main (String[] args)
Static Protected Attributes
static AppLoggingAgent logger = new AppLoggingAgent(new AppLoggingStream())
The AppLoggingAgent class represents an agent responsible for logging application events.
Private Attributes
HttpServer server
Represents the HTTP server for the shopping system.
ExecutorService threadPoolExecutor
The executor service used for managing threads in the web server.
Integer queueDepth
The maximum depth of the queue for incoming requests.
Integer port = Integer.parseInt(System.getenv().containsKey("PORT") ? System.getenv("PORT") : "8001")
The port number for the web server.
Integer maxThreads
The maximum number of threads that the web server can handle.
String hostname = System.getenv().containsKey("HOST_NAME") ? System.getenv("HOST_NAME") : "0.0.0.0"
The hostname of the web server.
Detailed Description
The WebServer class represents a web server that listens for HTTP requests and handles them accordingly.
Definition at line 18 of file WebServer.java.
Constructor & Destructor Documentation
WebServer()
WebServer.WebServer ()
Definition at line 61 of file WebServer.java.
                       {
        this.threadPoolExecutor = Executors.newFixedThreadPool(maxThreads);
        try {
            this.server = HttpServer.create(new InetSocketAddress(this.hostname, this.port), queueDepth);
            this.server.setExecutor(threadPoolExecutor);
        } catch (IOException e) {
            System.out.println("Error creating server");
        }
    }
References IFactory< T >.create(), maxThreads, queueDepth, and threadPoolExecutor.
Referenced by main().
Member Function Documentation
addRoute() [1/2]
HttpContext WebServer.addRoute (String route, HttpHandler handler)
Adds a route to the web server.
Parameters
route the route to be added
handler the handler for the route
Returns
the HttpContext object representing the added route
Definition at line 91 of file WebServer.java.
                                                                   {
        return addRoute(route, handler, null);
    }
References addRoute().
Referenced by addRoute(), and ShoppingWebInterfaceController.configure().
addRoute() [2/2]
HttpContext WebServer.addRoute (String route, HttpHandler handler, com.sun.net.httpserver.Authenticator authenticator)
Adds a route to the web server with the specified route path, handler, and authenticator.
Parameters
route The route path for the request.
handler The handler to be executed for the route.
authenticator The authenticator to be used for the route.
Returns
The HttpContext object representing the added route, or null if an error occurred.
Definition at line 103 of file WebServer.java.
                                                                                                                       {
        try {
            HttpContext context = this.server.createContext(route, handler);
            if (authenticator != null) {
                context.setAuthenticator(authenticator);
            }
            return context;
        } catch (Exception e) {
            logger.log("Error adding route", e);
            return null;
        }
    }
References logger.
main()
static void WebServer.main (String[] args) [static]
Definition at line 116 of file WebServer.java.
                                           {
        WebServer server = new WebServer();
        server.addRoute("/", new EchoHandler());
        server.addRoute("/echo/", new EchoHandler());
        server.start();
    }
References server, and WebServer().
start()
void WebServer.start ()
Starts the web server.
Definition at line 74 of file WebServer.java.
                        {
        logger.log("Server started");
        try {
            server.start();
            logger.log(" Starting server at => " + this.hostname + ":" + this.port);
        } catch (Exception e) {
            logger.log("Error running server", e);
        }
    }
References logger, and server.
Referenced by ShoppingSystem.start().
Member Data Documentation
hostname
String WebServer.hostname = System.getenv().containsKey("HOST_NAME") ? System.getenv("HOST_NAME") : "0.0.0.0" [private]
The hostname of the web server.
It is determined by the value of the "HOST_NAME" environment variable, or defaults to "0.0.0.0" if the environment variable is not set.
Definition at line 59 of file WebServer.java.
logger
AppLoggingAgent WebServer.logger = new AppLoggingAgent(new AppLoggingStream()) [static], [protected]
The AppLoggingAgent class represents an agent responsible for logging application events.
It provides methods to log messages, errors, and other events.
Definition at line 24 of file WebServer.java.
Referenced by addRoute(), and start().
maxThreads
Integer WebServer.maxThreads [private]
Initial value:
= Integer
            .parseInt(System.getenv().containsKey("MAX_THREADS") ? System.getenv("MAX_THREADS") : "25")
The maximum number of threads that the web server can handle.
The value is obtained from the environment variable "MAX_THREADS". If the environment variable is not set, the default value is 25.
Definition at line 52 of file WebServer.java.
Referenced by WebServer().
port
Integer WebServer.port = Integer.parseInt(System.getenv().containsKey("PORT") ? System.getenv("PORT") : "8001") [private]
The port number for the web server.
If the environment variable "PORT" is set, the port number will be parsed from it. Otherwise, the default port number is 8001.
Definition at line 46 of file WebServer.java.
queueDepth
Integer WebServer.queueDepth [private]
Initial value:
= Integer
            .parseInt(System.getenv().containsKey("QUEUE_DEPTH") ? System.getenv("QUEUE_DEPTH") : "100")
The maximum depth of the queue for incoming requests.
The value is obtained from the environment variable "QUEUE_DEPTH". If the environment variable is not set, the default value is 100.
Definition at line 39 of file WebServer.java.
Referenced by WebServer().
server
HttpServer WebServer.server [private]
Represents the HTTP server for the shopping system.
Definition at line 28 of file WebServer.java.
Referenced by main(), and start().
threadPoolExecutor
ExecutorService WebServer.threadPoolExecutor [private]
The executor service used for managing threads in the web server.
Definition at line 32 of file WebServer.java.
Referenced by WebServer().
The documentation for this class was generated from the following file:
WebServer.java