IFactory< T > Class Template Reference
The IFactory class is a generic factory class that allows the creation of instances of a specified class type.
Classes
class InstanceHolder
Static Public Member Functions
static< T > void register (String registrationName, Class< T > instance)
The function registers a class with the factory.
static< T > T create (String factoryString)
The function returns an instance of the IFactory class.
static< T > String convertUrlToString (final InputStream input, final String string) throws IOException
The function converts the content of an InputStream into a String using the specified character encoding.
static String[] getRegistered ()
The function returns an array of strings representing the names of the registered classes.
static< T > IFactory< T > Instance ()
The function returns an instance of the IFactory class.
Protected Member Functions
IFactory ()
The function returns an instance of the IFactory class.
Static Package Functions
[static initializer]
Static Private Member Functions
static String transferReaderToWriter (InputStreamReader inputReader, StringWriter strWriter, char[] buffer) throws IOException
The function transfers data from an InputStreamReader to a StringWriter using a buffer.
static String transferReaderToWriter (InputStreamReader inputReader, StringWriter strWriter, char[] buffer, int numBytes) throws IOException
The function transfers data from an InputStreamReader to a StringWriter and returns the resulting string.
static void loadViaClassloader (ClassLoader classLoader, String packagePath) throws Exception
The function loads classes from a specified package path using a class loader.
static String[] getClassList (ClassLoader classLoader, String packagePath) throws IOException
The function takes a ClassLoader and a package path, retrieves the list of classes in that package, and returns an array of class names.
static void processPath (String strPath) throws ClassNotFoundException
The function processes a given path and loads a class if the path ends with ".class" and starts with "DbFactoryW_".
Static Private Attributes
static final Map< String, Class<?> > factoryTable = new HashMap<>()
static AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The function returns an instance of the AppLoggingAgent class.
Detailed Description
The IFactory class is a generic factory class that allows the creation of instances of a specified class type.
Definition at line 17 of file IFactory.java.
Constructor & Destructor Documentation
IFactory()
IFactory< T >.IFactory () [protected]
The function returns an instance of the IFactory class.
Definition at line 33 of file IFactory.java.
                         {
    }
Referenced by IFactory< T >.InstanceHolder< T >.INSTANCE().
Member Function Documentation
[static initializer]()
IFactory< T >.[static initializer] [static], [package]
convertUrlToString()
static< T > String IFactory< T >.convertUrlToString (final InputStream input, final String string) throws IOException [static]
The function converts the content of an InputStream into a String using the specified character encoding.
Parameters
input The input parameter is an InputStream, which represents the input stream from which the data will be read. This can be any type of input stream, such as a FileInputStream or a URLConnection.getInputStream().
string The "string" parameter in the method represents the character encoding to be used when converting the input stream to a string. It specifies the character set that should be used to interpret the bytes from the input stream and convert them into characters.
Returns
The method is returning a String.
Definition at line 106 of file IFactory.java.
                                                                                                                 {
        try (InputStreamReader inputStreamReader = new InputStreamReader(input, string)) {
            try (StringWriter stringWriter = new StringWriter()) {
                char[] buffer = new char[AppConstants.READ_BUFFER_SIZE];
                return transferReaderToWriter(inputStreamReader, stringWriter, buffer);
            }
        }
    }
References AppConstants.READ_BUFFER_SIZE, and IFactory< T >.transferReaderToWriter().
Referenced by IFactory< T >.getClassList().
create()
static< T > T IFactory< T >.create (String factoryString) [static]
The function returns an instance of the IFactory class.
Parameters
factoryString The parameter "factoryString" is a string that represents the name of the class to be created. It is used to create an instance of the IFactory class with the specified class type.
Definition at line 73 of file IFactory.java.
                                                     {
        logging.log("factoryString: " + factoryString);
        if (factoryTable.containsKey(factoryString)) {
            try {
                // have to force load so the static instance registration is called
                Class<?> clazz = factoryTable.get(factoryString);
                return (T) clazz.getDeclaredConstructor().newInstance();
            } catch (Exception e) {
                logging.log(e);
            }
        }
        return null;
    }
References IFactory< T >.factoryTable, AppLoggingAgent.log(), and IFactory< T >.logging.
Referenced by ShoppingDataLayerService.executeCommand(), ShoppingDataLayerService.executeQuery(), and WebServer.WebServer().
getClassList()
static String[] IFactory< T >.getClassList (ClassLoader classLoader, String packagePath) throws IOException [static], [private]
The function takes a ClassLoader and a package path, retrieves the list of classes in that package, and returns an array of class names.
Parameters
classLoader The "classLoader" parameter is the ClassLoader object that is used to load classes and resources. It is responsible for finding and loading classes at runtime.
packagePath The packagePath parameter is a string representing the path of the package containing the classes you want to retrieve. It should be in the format of a file system path, using forward slashes ("/") to separate directories.
Returns
The method is returning an array of strings.
Definition at line 224 of file IFactory.java.
                                                                                                         {
        String cleanPackagePath = packagePath.replaceAll("[/]", ".");
        URL classPackageUrl = classLoader.getResource(cleanPackagePath);
        URLConnection connection = classPackageUrl.openConnection();
        String classList = convertUrlToString(connection.getInputStream(), "UTF-8");
        return (classList != null) ? classList.split("\n") : new String[0];
    }
References IFactory< T >.convertUrlToString().
Referenced by IFactory< T >.loadViaClassloader().
getRegistered()
static String[] IFactory< T >.getRegistered () [static]
The function returns an array of strings representing the names of the registered classes.
Returns
The method is returning an array of strings.
Definition at line 239 of file IFactory.java.
                                           {
        List<String> registered = new ArrayList<String>(factoryTable.keySet());
        return registered.toArray(new String[registered.size()]);
    }
References IFactory< T >.factoryTable.
Instance()
static< T > IFactory< T > IFactory< T >.Instance () [static]
The function returns an instance of the IFactory class.
Returns
The method is returning an instance of the IFactory class.
Definition at line 276 of file IFactory.java.
                                             {
        return InstanceHolder.INSTANCE();
    }
References IFactory< T >.InstanceHolder< T >.INSTANCE().
loadViaClassloader()
static void IFactory< T >.loadViaClassloader (ClassLoader classLoader, String packagePath) throws Exception [static], [private]
The function loads classes from a specified package path using a class loader.
Parameters
classLoader The "classLoader" parameter is a ClassLoader object that is used to load classes and resources. It is responsible for finding and loading classes at runtime.
packagePath The packagePath parameter is a string representing the path to a package in the file system. It should be in the format of a file system path, using forward slashes ("/") to separate directories.
Definition at line 200 of file IFactory.java.
                                                                                                         {
        String[] classList = getClassList(classLoader, packagePath);
        for (String p : classList) {
            processPath(p);
        }
    }
References IFactory< T >.getClassList(), and IFactory< T >.processPath().
processPath()
static void IFactory< T >.processPath (String strPath) throws ClassNotFoundException [static], [private]
The function processes a given path and loads a class if the path ends with ".class" and starts with "DbFactoryW_".
Parameters
strPath The parameter "strPath" is a string representing a file path.
Definition at line 251 of file IFactory.java.
                                                                                  {
        if (strPath.endsWith(".class") && strPath.startsWith(AppConstants.DB_CLASSNAME_PREFIX)) {
            logging.log("loading class: " + strPath);
            Class.forName(strPath.substring(0, strPath.lastIndexOf('.')));
        }
    }
References AppConstants.DB_CLASSNAME_PREFIX, AppLoggingAgent.log(), and IFactory< T >.logging.
Referenced by IFactory< T >.loadViaClassloader().
register()
static< T > void IFactory< T >.register (String registrationName, Class< T > instance) [static]
The function registers a class with the factory.
Parameters
registrationName The parameter "registrationName" is a string that represents the name of the class to be registered. It is used to register a class with the factory.
instance The parameter "instance" is a Class object that represents the class to be registered. It is used to register a class with the factory.
Definition at line 58 of file IFactory.java.
                                                                                {
        if (registrationName != null && instance != null) {
            factoryTable.put(registrationName, instance);
        }
    }
References IFactory< T >.factoryTable.
Referenced by DbBaseFactoryWrapper_postgres.[static initializer]().
transferReaderToWriter() [1/2]
static String IFactory< T >.transferReaderToWriter (InputStreamReader inputReader, StringWriter strWriter, char[] buffer) throws IOException [static], [private]
The function transfers data from an InputStreamReader to a StringWriter using a buffer.
Parameters
inputReader The "inputReader" parameter is an InputStreamReader object, which is used to read characters from an input stream. It is the source from which characters will be read.
strWriter The parameter "strWriter" is a StringWriter object that is used to write the data read from the InputStreamReader.
buffer The buffer parameter is an array of characters that is used to store the data read from the InputStreamReader and write it to the StringWriter. It is used as a temporary storage for the data during the transfer process.
Returns
The method is returning a String.
Definition at line 138 of file IFactory.java.
                               {
        return transferReaderToWriter(inputReader, strWriter, buffer, 0);
    }
References IFactory< T >.transferReaderToWriter().
Referenced by IFactory< T >.convertUrlToString(), and IFactory< T >.transferReaderToWriter().
transferReaderToWriter() [2/2]
static String IFactory< T >.transferReaderToWriter (InputStreamReader inputReader, StringWriter strWriter, char[] buffer, int numBytes) throws IOException [static], [private]
The function transfers data from an InputStreamReader to a StringWriter and returns the resulting string.
Parameters
inputReader The "inputReader" parameter is an InputStreamReader, which is used to read characters from an InputStream. It is the input source from which characters will be read.
strWriter The parameter "strWriter" is a StringWriter object. It is used to write the contents read from the InputStreamReader.
buffer The buffer parameter is a character array used to store the data read from the InputStreamReader and write to the StringWriter. It is used to read and write data in chunks, rather than one character at a time, which can improve performance. The size of the buffer determines how
numBytes The parameter "numBytes" is an integer that represents the number of characters read from the input stream. It is used to keep track of the number of characters read in each iteration of the while loop.
Returns
The method is returning a String.
Definition at line 176 of file IFactory.java.
                               {
        while (AppConstants.EOF != (numBytes = inputReader.read(buffer))) {
            strWriter.write(buffer, 0, numBytes);
        }
        return strWriter.toString();
    }
References AppConstants.EOF.
Member Data Documentation
factoryTable
final Map<String, Class<?> > IFactory< T >.factoryTable = new HashMap<>() [static], [private]
Definition at line 21 of file IFactory.java.
Referenced by IFactory< T >.create(), IFactory< T >.getRegistered(), and IFactory< T >.register().
logging
AppLoggingAgent IFactory< T >.logging = new AppLoggingAgent(new AppLoggingStream()) [static], [private]
The function returns an instance of the AppLoggingAgent class.
Returns
The method is returning an instance of the AppLoggingAgent class.
Definition at line 28 of file IFactory.java.
Referenced by IFactory< T >.create(), and IFactory< T >.processPath().
The documentation for this class was generated from the following file:
IFactory.java