TestDTO Class Reference
Package Functions
void testUserDTO_1 ()
void testUserDTO_2 ()
void testUserDTO_3 ()
void testRoleDTO_1 ()
void testRoleDTO_2 ()
void testProductDTO_1 ()
void testProductDTO_2 ()
void testProductDTO_3 ()
void testProductDTO_4 ()
void testPaymentProfileDTO_1 ()
void testPaymentProfileDTO_2 ()
void testUserProfileDTO_1 ()
void testUserProfileDTO_2 ()
void testPurchaseDTO_1 ()
void testPurchaseDTO_2 ()
void testCartDTO_1 ()
void testCartDTO_2 ()
void testCartItemDTO_1 ()
void testCartItemDTO_2 ()
void testUserRoleDTO_1 ()
void testUserRoleDTO_2 ()
void testOrderDTO_1 ()
void testOrderDTO_2 ()
void testOrderItemDTO_1 ()
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
Detailed Description
Definition at line 12 of file TestDTO.java.
Member Function Documentation
testCartDTO_1()
void TestDTO.testCartDTO_1 () [package]
Definition at line 392 of file TestDTO.java.
                         {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        CartDTO dto = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("status", "pending");
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (CartDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CartDTOHome.Instance(), Environment.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testCartDTO_2()
void TestDTO.testCartDTO_2 () [package]
Definition at line 414 of file TestDTO.java.
                         {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "jillsample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        CartDTO dto = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("status", "complete");
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (CartDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CartDTOHome.Instance(), Environment.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testCartItemDTO_1()
void TestDTO.testCartItemDTO_1 () [package]
Definition at line 445 of file TestDTO.java.
                             {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        CartDTO cdto = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        cdto.setValue("user_id", udto.getValue("id"));
        cdto.setValue("status", "pending");
        List<IDTO> carts = dataLayerService.loadDTOs(cdto, cdto.getDtoHome());
        cdto = (CartDTO) carts.getFirst();
        ProductDTO pdto = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "car");
        List<IDTO> products = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (ProductDTO) products.getFirst();
        CartItemDTO dto = (CartItemDTO) CartItemDTOHome.Instance().newDTOInstance();
        dto.setValue("cart_id", cdto.getValue("id"));
        dto.setValue("product_id", pdto.getValue("id"));
        dto.setValue("quantity", 2);
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (CartItemDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CartDTOHome.Instance(), CartItemDTOHome.Instance(), Environment.Instance(), ProductDTOHome.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testCartItemDTO_2()
void TestDTO.testCartItemDTO_2 () [package]
Definition at line 479 of file TestDTO.java.
                             {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        CartDTO cdto = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        cdto.setValue("user_id", udto.getValue("id"));
        cdto.setValue("status", "pending");
        List<IDTO> carts = dataLayerService.loadDTOs(cdto, cdto.getDtoHome());
        cdto = (CartDTO) carts.getFirst();
        ProductDTO pdto = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "gasoline");
        List<IDTO> products = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (ProductDTO) products.getFirst();
        CartItemDTO dto = (CartItemDTO) CartItemDTOHome.Instance().newDTOInstance();
        dto.setValue("cart_id", cdto.getValue("id"));
        dto.setValue("product_id", pdto.getValue("id"));
        dto.setValue("quantity", 10);
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (CartItemDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CartDTOHome.Instance(), CartItemDTOHome.Instance(), Environment.Instance(), ProductDTOHome.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testOrderDTO_1()
void TestDTO.testOrderDTO_1 () [package]
Definition at line 583 of file TestDTO.java.
                          {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        CartDTO cdto = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        cdto.setValue("user_id", udto.getValue("id"));
        cdto.setValue("status", "pending");
        List<IDTO> carts = dataLayerService.loadDTOs(cdto, cdto.getDtoHome());
        cdto = (CartDTO) carts.getFirst();
        PaymentProfileDTO padto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        padto.setValue("name", "ach");
        List<IDTO> profiles = dataLayerService.loadDTOs(padto, padto.getDtoHome());
        padto = (PaymentProfileDTO) profiles.getFirst();
        PurchaseDTO pudto = (PurchaseDTO) PurchaseDTOHome.Instance().newDTOInstance();
        pudto.setValue("user_id", udto.getValue("id"));
        pudto.setValue("paymentprofile_id", padto.getValue("id"));
        List<IDTO> purchases = dataLayerService.loadDTOs(pudto, pudto.getDtoHome());
        pudto = (PurchaseDTO) purchases.getFirst();
        OrderDTO dto = (OrderDTO) OrderDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("cart_id", cdto.getValue("id"));
        dto.setValue("purchase_id", pudto.getValue("id"));
        dto.setValue("status", "pending");
        List<IDTO> orders = dataLayerService.saveDTO(dto);
        dto = (OrderDTO) orders.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CartDTOHome.Instance(), Environment.Instance(), OrderDTOHome.Instance(), PaymentProfileDTOHome.Instance(), PurchaseDTOHome.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testOrderDTO_2()
void TestDTO.testOrderDTO_2 () [package]
Definition at line 623 of file TestDTO.java.
                          {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        CartDTO cdto = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        cdto.setValue("user_id", udto.getValue("id"));
        cdto.setValue("status", "pending");
        List<IDTO> carts = dataLayerService.loadDTOs(cdto, cdto.getDtoHome());
        cdto = (CartDTO) carts.getFirst();
        PaymentProfileDTO pdto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "cc");
        List<IDTO> profiles = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (PaymentProfileDTO) profiles.getFirst();
        PurchaseDTO pudto = (PurchaseDTO) PurchaseDTOHome.Instance().newDTOInstance();
        pudto.setValue("user_id", udto.getValue("id"));
        pudto.setValue("paymentprofile_id", pdto.getValue("id"));
        List<IDTO> purchases = dataLayerService.saveDTO(pudto);
        pudto = (PurchaseDTO) purchases.getFirst();
        OrderDTO dto = (OrderDTO) OrderDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("cart_id", cdto.getValue("id"));
        dto.setValue("purchase_id", pudto.getValue("id"));
        dto.setValue("status", "pending");
        List<IDTO> orders = dataLayerService.saveDTO(dto);
        dto = (OrderDTO) orders.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CartDTOHome.Instance(), Environment.Instance(), OrderDTOHome.Instance(), PaymentProfileDTOHome.Instance(), PurchaseDTOHome.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testOrderItemDTO_1()
void TestDTO.testOrderItemDTO_1 () [package]
Definition at line 671 of file TestDTO.java.
                              {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        CartDTO cdto = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        cdto.setValue("user_id", udto.getValue("id"));
        cdto.setValue("status", "pending");
        List<IDTO> carts = dataLayerService.loadDTOs(cdto, cdto.getDtoHome());
        cdto = (CartDTO) carts.getFirst();
        ProductDTO pdto = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "car");
        List<IDTO> products = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (ProductDTO) products.getFirst();
        PaymentProfileDTO padto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        padto.setValue("name", "ach");
        List<IDTO> profiles = dataLayerService.loadDTOs(padto, padto.getDtoHome());
        padto = (PaymentProfileDTO) profiles.getFirst();
        PurchaseDTO pudto = (PurchaseDTO) PurchaseDTOHome.Instance().newDTOInstance();
        pudto.setValue("user_id", udto.getValue("id"));
        pudto.setValue("paymentprofile_id", padto.getValue("id"));
        List<IDTO> purchases = dataLayerService.loadDTOs(pudto, pudto.getDtoHome());
        pudto = (PurchaseDTO) purchases.getFirst();
        CartItemDTO cidto = (CartItemDTO) CartItemDTOHome.Instance().newDTOInstance();
        cidto.setValue("cart_id", cdto.getValue("id"));
        cidto.setValue("product_id", pdto.getValue("id"));
        cidto.setValue("quantity", 2);
        List<IDTO> cartitems = dataLayerService.loadDTOs(cidto, cidto.getDtoHome());
        cidto = (CartItemDTO) cartitems.getFirst();
        OrderDTO odto = (OrderDTO) OrderDTOHome.Instance().newDTOInstance();
        odto.setValue("user_id", udto.getValue("id"));
        odto.setValue("cart_id", cdto.getValue("id"));
        odto.setValue("purchase_id", pudto.getValue("id"));
        odto.setValue("status", "pending");
        List<IDTO> orders = dataLayerService.loadDTOs(odto, odto.getDtoHome());
        odto = (OrderDTO) orders.getFirst();
        OrderItemDTO dto = (OrderItemDTO) OrderItemDTOHome.Instance().newDTOInstance();
        dto.setValue("cartitem_id", cidto.getValue("id"));
        dto.setValue("order_id", odto.getValue("id"));
        dto.setValue("price", 125000.0);
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (OrderItemDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CartDTOHome.Instance(), CartItemDTOHome.Instance(), Environment.Instance(), OrderDTOHome.Instance(), OrderItemDTOHome.Instance(), PaymentProfileDTOHome.Instance(), ProductDTOHome.Instance(), PurchaseDTOHome.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testPaymentProfileDTO_1()
void TestDTO.testPaymentProfileDTO_1 () [package]
Definition at line 225 of file TestDTO.java.
                                   {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        PaymentProfileDTO dto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "ach");
        dto.setValue("description", "banking");
        dto.setValue("type", "ach");
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (PaymentProfileDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), PaymentProfileDTOHome.Instance(), and AppLoggingAgent.log().
testPaymentProfileDTO_2()
void TestDTO.testPaymentProfileDTO_2 () [package]
Definition at line 244 of file TestDTO.java.
                                   {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        PaymentProfileDTO dto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "cc");
        dto.setValue("description", "creditcard");
        dto.setValue("type", "cc");
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (PaymentProfileDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), PaymentProfileDTOHome.Instance(), and AppLoggingAgent.log().
testProductDTO_1()
void TestDTO.testProductDTO_1 () [package]
Definition at line 141 of file TestDTO.java.
                            {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        ProductDTO dto = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "cleaner");
        dto.setValue("description", "soap");
        dto.setValue("price", 10.0);
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (ProductDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), ProductDTOHome.Instance(), and AppLoggingAgent.log().
testProductDTO_2()
void TestDTO.testProductDTO_2 () [package]
Definition at line 160 of file TestDTO.java.
                            {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        ProductDTO dto = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "gasoline");
        dto.setValue("description", "UNL92");
        dto.setValue("price", 4.5);
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (ProductDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), ProductDTOHome.Instance(), and AppLoggingAgent.log().
testProductDTO_3()
void TestDTO.testProductDTO_3 () [package]
Definition at line 179 of file TestDTO.java.
                            {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        ProductDTO dto = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "tires");
        dto.setValue("description", "runflats");
        dto.setValue("price", 300.0);
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (ProductDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), ProductDTOHome.Instance(), and AppLoggingAgent.log().
testProductDTO_4()
void TestDTO.testProductDTO_4 () [package]
Definition at line 198 of file TestDTO.java.
                            {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        ProductDTO dto = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "car");
        dto.setValue("description", "porsche");
        dto.setValue("price", 300000.0);
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (ProductDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), ProductDTOHome.Instance(), and AppLoggingAgent.log().
testPurchaseDTO_1()
void TestDTO.testPurchaseDTO_1 () [package]
Definition at line 331 of file TestDTO.java.
                             {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        PaymentProfileDTO pdto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "ach");
        List<IDTO> profiles = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (PaymentProfileDTO) profiles.getFirst();
        PurchaseDTO dto = (PurchaseDTO) PurchaseDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("paymentprofile_id", pdto.getValue("id"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (PurchaseDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), PaymentProfileDTOHome.Instance(), PurchaseDTOHome.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testPurchaseDTO_2()
void TestDTO.testPurchaseDTO_2 () [package]
Definition at line 358 of file TestDTO.java.
                             {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "jillsample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        PaymentProfileDTO pdto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "cc");
        List<IDTO> profiles = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (PaymentProfileDTO) profiles.getFirst();
        PurchaseDTO dto = (PurchaseDTO) PurchaseDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("paymentprofile_id", pdto.getValue("id"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (PurchaseDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), PaymentProfileDTOHome.Instance(), PurchaseDTOHome.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testRoleDTO_1()
void TestDTO.testRoleDTO_1 () [package]
Definition at line 97 of file TestDTO.java.
                         {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        RoleDTO dto = (RoleDTO) RoleDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "admin");
        dto.setValue("description", "administrator");
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (RoleDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), RoleDTOHome.Instance(), and AppLoggingAgent.log().
testRoleDTO_2()
void TestDTO.testRoleDTO_2 () [package]
Definition at line 115 of file TestDTO.java.
                         {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        RoleDTO dto = (RoleDTO) RoleDTOHome.Instance().newDTOInstance();
        dto.setValue("name", "user");
        dto.setValue("description", "user");
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (RoleDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), RoleDTOHome.Instance(), and AppLoggingAgent.log().
testUserDTO_1()
void TestDTO.testUserDTO_1 () [package]
Definition at line 28 of file TestDTO.java.
                         {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO dto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        dto.setValue("first_name", "admin");
        dto.setValue("last_name", "admin");
        dto.setValue("email_address", "admin");
        dto.setValue("password_hash", CoreUtils.encodeSha256String("admin"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (UserDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CoreUtils.encodeSha256String(), Environment.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testUserDTO_2()
void TestDTO.testUserDTO_2 () [package]
Definition at line 48 of file TestDTO.java.
                         {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO dto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        dto.setValue("first_name", "joe");
        dto.setValue("last_name", "sample");
        dto.setValue("email_address", "joesample");
        dto.setValue("password_hash", CoreUtils.encodeSha256String("joesample"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (UserDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CoreUtils.encodeSha256String(), Environment.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testUserDTO_3()
void TestDTO.testUserDTO_3 () [package]
Definition at line 68 of file TestDTO.java.
                         {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO dto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        dto.setValue("first_name", "jill");
        dto.setValue("last_name", "sample");
        dto.setValue("email_address", "jillsample");
        dto.setValue("password_hash", CoreUtils.encodeSha256String("jillsample"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (UserDTO) result.get(0);
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References CoreUtils.encodeSha256String(), Environment.Instance(), UserDTOHome.Instance(), and AppLoggingAgent.log().
testUserProfileDTO_1()
void TestDTO.testUserProfileDTO_1 () [package]
Definition at line 270 of file TestDTO.java.
                                {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        PaymentProfileDTO pdto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "ach");
        List<IDTO> profiles = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (PaymentProfileDTO) profiles.getFirst();
        UserProfileDTO dto = (UserProfileDTO) UserProfileDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("paymentprofile_id", pdto.getValue("id"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (UserProfileDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), PaymentProfileDTOHome.Instance(), UserDTOHome.Instance(), UserProfileDTOHome.Instance(), and AppLoggingAgent.log().
testUserProfileDTO_2()
void TestDTO.testUserProfileDTO_2 () [package]
Definition at line 297 of file TestDTO.java.
                                {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "jillsample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        PaymentProfileDTO pdto = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        pdto.setValue("name", "cc");
        List<IDTO> profiles = dataLayerService.loadDTOs(pdto, pdto.getDtoHome());
        pdto = (PaymentProfileDTO) profiles.getFirst();
        UserProfileDTO dto = (UserProfileDTO) UserProfileDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("paymentprofile_id", pdto.getValue("id"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (UserProfileDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), PaymentProfileDTOHome.Instance(), UserDTOHome.Instance(), UserProfileDTOHome.Instance(), and AppLoggingAgent.log().
testUserRoleDTO_1()
void TestDTO.testUserRoleDTO_1 () [package]
Definition at line 520 of file TestDTO.java.
                             {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "joesample");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        RoleDTO rdto = (RoleDTO) RoleDTOHome.Instance().newDTOInstance();
        rdto.setValue("name", "user");
        List<IDTO> roles = dataLayerService.loadDTOs(rdto, rdto.getDtoHome());
        rdto = (RoleDTO) roles.getFirst();
        UserRoleDTO dto = (UserRoleDTO) UserRoleDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("role_id", rdto.getValue("id"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (UserRoleDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), RoleDTOHome.Instance(), UserDTOHome.Instance(), UserRoleDTOHome.Instance(), and AppLoggingAgent.log().
testUserRoleDTO_2()
void TestDTO.testUserRoleDTO_2 () [package]
Definition at line 547 of file TestDTO.java.
                             {
        ShoppingDataLayerService dataLayerService = new ShoppingDataLayerService(Environment.Instance());
        dataLayerService.configure();
        UserDTO udto = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        udto.setValue("email_address", "admin");
        List<IDTO> users = dataLayerService.loadDTOs(udto, udto.getDtoHome());
        udto = (UserDTO) users.getFirst();
        RoleDTO rdto = (RoleDTO) RoleDTOHome.Instance().newDTOInstance();
        rdto.setValue("name", "admin");
        List<IDTO> roles = dataLayerService.loadDTOs(rdto, rdto.getDtoHome());
        rdto = (RoleDTO) roles.getFirst();
        UserRoleDTO dto = (UserRoleDTO) UserRoleDTOHome.Instance().newDTOInstance();
        dto.setValue("user_id", udto.getValue("id"));
        dto.setValue("role_id", rdto.getValue("id"));
        List<IDTO> result = dataLayerService.saveDTO(dto);
        dto = (UserRoleDTO) result.getFirst();
        logging.log(dto);
        assertNotNull(dto.getValue("id"));
    }
References Environment.Instance(), RoleDTOHome.Instance(), UserDTOHome.Instance(), UserRoleDTOHome.Instance(), and AppLoggingAgent.log().
Member Data Documentation
logging
AppLoggingAgent TestDTO.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
Definition at line 14 of file TestDTO.java.
The documentation for this class was generated from the following file:
TestDTO.java