DbBaseFactoryWrapper_postgres Class Reference
The class is a factory for creating instances of the IDbConnectionWrapper interface.
Public Member Functions
DbBaseFactoryWrapper_postgres ()
String buildJdbcUrl ()
The function builds the jdbc url for the database.
Public Member Functions inherited from DbBaseFactoryWrapper
String getUsername ()
The function returns the username for the database.
void setUsername (String username)
The function sets the username for the database.
String getPassword ()
The function returns the password for the database.
void setPassword (String password)
The function sets the password for the database.
String getHost ()
The function returns the host for the database.
void setHost (String host)
The function sets the host for the database.
String getDatabase ()
The function returns the database name.
void setDatabase (String database)
The function sets the database name.
int getPort ()
The function returns the port for the database.
void setPort (int port)
The function sets the port for the database.
String getUrl ()
The function returns the url for the database.
void setUrl (String url)
The function sets the url for the database.
String getSchema ()
void setSchema (String schema)
DbBaseFactoryWrapper ()
void connectionProperties (String user, String pass, int port, String host, String database, String schema)
The function sets the connection properties.
void close () throws IOException
The function closes the connection to the database.
Boolean query (String query, IDbResultProcessor resultProcessor)
Executes the given query on the database and processes the result using the provided IDbResultProcessor.
Boolean execute (String query, IDbResultProcessor resultProcessor)
Executes the given query and processes the result using the provided IDbResultProcessor.
Static Package Functions
[static initializer]
Static Package Functions inherited from IFactory< IDbConnectionWrapper >
[static initializer]
Additional Inherited Members
Static Public Member Functions inherited from IFactory< IDbConnectionWrapper >
static< T > void register (String registrationName, Class< T > instance)
The function registers a class with the factory.
static< T > T create (String factoryString)
The function returns an instance of the IFactory class.
static< T > String convertUrlToString (final InputStream input, final String string) throws IOException
The function converts the content of an InputStream into a String using the specified character encoding.
static String[] getRegistered ()
The function returns an array of strings representing the names of the registered classes.
static< T > IFactory< T > Instance ()
The function returns an instance of the IFactory class.
Protected Member Functions inherited from IFactory< IDbConnectionWrapper >
IFactory ()
The function returns an instance of the IFactory class.
Static Protected Attributes inherited from DbBaseFactoryWrapper
static AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The function returns an instance of the AppLoggingAgent class.
Detailed Description
The class is a factory for creating instances of the IDbConnectionWrapper interface.
Definition at line 6 of file DbBaseFactoryWrapper_postgres.java.
Constructor & Destructor Documentation
DbBaseFactoryWrapper_postgres()
DbBaseFactoryWrapper_postgres.DbBaseFactoryWrapper_postgres ()
Definition at line 11 of file DbBaseFactoryWrapper_postgres.java.
                                           {
        try {
            Class.forName("org.postgresql.Driver").getDeclaredConstructor().newInstance();
        } catch (Exception e) {
            logging.log(e);
        }
    }
References AppLoggingAgent.log(), and DbBaseFactoryWrapper.logging.
Member Function Documentation
[static initializer]()
DbBaseFactoryWrapper_postgres.[static initializer] [static], [package]
References IFactory< T >.register().
buildJdbcUrl()
String DbBaseFactoryWrapper_postgres.buildJdbcUrl ()
The function builds the jdbc url for the database.
Returns
The method is returning the jdbc url for the database.
Reimplemented from DbBaseFactoryWrapper.
Definition at line 25 of file DbBaseFactoryWrapper_postgres.java.
                                 {
        return "jdbc:postgresql://" + this.getHost() + ":" + this.getPort() + "/" + this.getDatabase();
    }
References DbBaseFactoryWrapper.getDatabase(), DbBaseFactoryWrapper.getHost(), and DbBaseFactoryWrapper.getPort().
The documentation for this class was generated from the following file:
DbBaseFactoryWrapper_postgres.java