BaseDTOHome Class Reference
Public Member Functions
abstract IDTO newDTOInstance ()
Creates a new instance of the DTO.
List< IDTO > queryDTOs (IDTO dtoQuery)
Queries the database for a list of DTOs based on the provided query DTO.
Boolean saveDTO (IDTO dto)
Saves a single DTO object.
Boolean saveDTOs (List< IDTO > dtos)
Saves a list of DTOs.
IDbResultProcessor getLoadProcessor ()
Gets the result processor for loading data from the database.
String getLoadSql (IDTO dto)
Returns the SQL query for loading data from the database based on the provided DTO object.
IDbResultProcessor getSaveProcessor (IDTO dto)
The function returns an instance of a class that implements the IDbResultProcessor interface, which processes the result set from a database save operation and returns a list of DTO objects.
String getSaveSql (IDTO dto)
Returns the SQL statement for saving the given DTO.
Protected Member Functions
Boolean processLoadResult (ResultSet rs, List< IDTO > results) throws SQLException
Processes the load result from a ResultSet and populates a list of DTO objects.
Boolean processLoadResult (ResultSet rs, IDTO dto) throws SQLException
Processes the load result from a ResultSet and sets the values in the given DTO.
Object getValueFromResultSet (ResultSet rs, String fieldName, DTOTypes dtoTypes) throws SQLException
Retrieves the value from the ResultSet based on the field name and data type.
String formatValueForQuery (Object value, DTOTypes dtoTypes)
Formats the given value for query based on the specified DTO type.
Boolean processSaveResult (ResultSet rs, IDTO dto, List< IDTO > saveResults) throws SQLException
Processes the save result from the database and updates the DTO object accordingly.
void buildInsertSql (StringBuilder sb, IDTO dto)
Builds the SQL query for inserting data into the database table.
void buildUpdateSql (StringBuilder sb, IDTO dto)
Builds an SQL update statement for the given DTO object.
Detailed Description
Definition at line 10 of file BaseDTOHome.java.
Member Function Documentation
buildInsertSql()
void BaseDTOHome.buildInsertSql (StringBuilder sb, IDTO dto) [protected]
Builds the SQL query for inserting data into the database table.
Parameters
sb The StringBuilder object to store the SQL query.
dto The DTO object containing the data to be inserted.
Definition at line 272 of file BaseDTOHome.java.
                                                              {
        sb.append("INSERT INTO " + dto.getDtoName() + " (");
        for (Map.Entry<String, DTOTypes> entry : dto.getFields().entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = dto.getValue(fieldName);
            sb.append(fieldName + ", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        sb.append(") VALUES (");
        for (Map.Entry<String, DTOTypes> entry : dto.getFields().entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = dto.getValue(fieldName);
            sb.append(formatValueForQuery(value, fieldType) + ", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        sb.append(")");
    }
References formatValueForQuery(), IDTO.getDtoName(), IDTO.getFields(), and IDTO.getValue().
Referenced by getSaveSql().
buildUpdateSql()
void BaseDTOHome.buildUpdateSql (StringBuilder sb, IDTO dto) [protected]
Builds an SQL update statement for the given DTO object.
Parameters
sb The StringBuilder to append the SQL statement to.
dto The DTO object containing the data to be updated.
Definition at line 298 of file BaseDTOHome.java.
                                                              {
        sb.append("UPDATE " + dto.getDtoName() + " SET ");
        for (Map.Entry<String, DTOTypes> entry : dto.getFields().entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = dto.getValue(fieldName);
            sb.append(fieldName + " = " + formatValueForQuery(value, fieldType) + ", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        sb.append(" WHERE id = " + dto.getValue("id"));
    }
References formatValueForQuery(), IDTO.getDtoName(), IDTO.getFields(), and IDTO.getValue().
Referenced by getSaveSql().
formatValueForQuery()
String BaseDTOHome.formatValueForQuery (Object value, DTOTypes dtoTypes) [protected]
Formats the given value for query based on the specified DTO type.
Parameters
value the value to be formatted
dtoTypes the DTO type
Returns
the formatted value for query
Definition at line 118 of file BaseDTOHome.java.
                                                                          {
        switch (dtoTypes) {
            case INTEGER:
                return value + "";
            case DATE:
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss z");
                sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
                return formatValueForQuery(sdf.format(value), DTOTypes.STRING);
            case FLOAT:
                return value + "";
            default:
                return "'" + value + "'";
        }
    }
References formatValueForQuery(), and DTOTypes.STRING.
Referenced by buildInsertSql(), buildUpdateSql(), formatValueForQuery(), and getLoadSql().
getLoadProcessor()
IDbResultProcessor BaseDTOHome.getLoadProcessor ()
Gets the result processor for loading data from the database.
Returns
The result processor for loading data from the database.
Implements IDTOHome.
Definition at line 139 of file BaseDTOHome.java.
                                                 {
        class LoadResultProcessor implements IDbResultProcessor {
            private IDTOHome dtoHome;
            LoadResultProcessor(IDTOHome dtoHome) {
                this.dtoHome = dtoHome;
            }
            @Override
            public Boolean process(ResultSet rs) throws SQLException {
                return processLoadResult(rs, loadResults);
            }
            private List<IDTO> loadResults = new ArrayList<>();
            public List<IDTO> getResults() {
                return loadResults;
            }
        }
        return new LoadResultProcessor(this);
    }
getLoadSql()
String BaseDTOHome.getLoadSql (IDTO dto)
Returns the SQL query for loading data from the database based on the provided DTO object.
Parameters
dto The DTO object containing the information for constructing the SQL query.
Returns
The SQL query string.
Definition at line 170 of file BaseDTOHome.java.
                                       {
        StringBuilder sb = new StringBuilder();
        Boolean isFirst = true;
        sb.append("SELECT * FROM " + dto.getDtoName() + " WHERE ");
        for (Map.Entry<String, DTOTypes> entry : dto.getFields().entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = dto.getValue(fieldName);
            if (!isFirst)
                sb.append(" AND ");
            else
                isFirst = false;
            sb.append(fieldName + " = " + formatValueForQuery(value, fieldType));
        }
        return sb.toString();
    }
References formatValueForQuery(), IDTO.getDtoName(), IDTO.getFields(), and IDTO.getValue().
getSaveProcessor()
IDbResultProcessor BaseDTOHome.getSaveProcessor (IDTO dto)
The function returns an instance of a class that implements the IDbResultProcessor interface, which processes the result set from a database save operation and returns a list of DTO objects.
Parameters
dto The parameter "dto" is an object of type IDTO, which is an interface representing a data transfer object. It is used as input to the SaveResultProcessor class constructor.
Returns
The method is returning an instance of the inner class SaveResultProcessor, which implements the IDbResultProcessor interface.
Definition at line 225 of file BaseDTOHome.java.
                                                         {
        class SaveResultProcessor implements IDbResultProcessor {
            private IDTO dto;
            SaveResultProcessor(IDTO dto) {
                this.dto = dto;
            }
            @Override
            public Boolean process(ResultSet rs) throws SQLException {
                return processSaveResult(rs, this.dto, saveResults);
            }
            private List<IDTO> saveResults = new ArrayList<>();
            public List<IDTO> getResults() {
                return saveResults;
            }
        }
        return new SaveResultProcessor(dto);
    }
getSaveSql()
String BaseDTOHome.getSaveSql (IDTO dto)
Returns the SQL statement for saving the given DTO.
Parameters
dto The DTO object to be saved.
Returns
The SQL statement for saving the DTO.
Definition at line 253 of file BaseDTOHome.java.
                                       {
        StringBuilder sb = new StringBuilder();
        Object value = dto.getValue("id");
        Boolean isInsert = value == null;
        if (isInsert)
            buildInsertSql(sb, dto);
        else
            buildUpdateSql(sb, dto);
        return sb.toString();
    }
References buildInsertSql(), buildUpdateSql(), and IDTO.getValue().
getValueFromResultSet()
Object BaseDTOHome.getValueFromResultSet (ResultSet rs, String fieldName, DTOTypes dtoTypes) throws SQLException [protected]
Retrieves the value from the ResultSet based on the field name and data type.
Parameters
rs the ResultSet object
fieldName the name of the field in the ResultSet
dtoTypes the data type of the field
Returns
the value retrieved from the ResultSet
Exceptions
SQLException if a database access error occurs
Definition at line 98 of file BaseDTOHome.java.
                                                                                                                  {
        switch (dtoTypes) {
            case INTEGER:
                return rs.getInt(fieldName);
            case DATE:
                return rs.getDate(fieldName);
            case FLOAT:
                return rs.getFloat(fieldName);
            default:
                return rs.getString(fieldName);
        }
    }
Referenced by processLoadResult(), and processSaveResult().
newDTOInstance()
abstract IDTO BaseDTOHome.newDTOInstance () [abstract]
Creates a new instance of the DTO.
Returns
A new instance of the DTO.
Implements IDTOHome.
Reimplemented in AuditTrailDTOHome, CartDTOHome, CartItemDTOHome, OrderDTOHome, OrderItemDTOHome, PaymentProfileDTOHome, ProductDTOHome, PurchaseDTOHome, RoleDTOHome, UserDTOHome, UserProfileDTOHome, and UserRoleDTOHome.
Referenced by processLoadResult().
processLoadResult() [1/2]
Boolean BaseDTOHome.processLoadResult (ResultSet rs, IDTO dto) throws SQLException [protected]
Processes the load result from a ResultSet and sets the values in the given DTO.
Parameters
rs The ResultSet containing the data to be processed.
dto The DTO object to set the values in.
Returns
true if the load result was successfully processed, false otherwise.
Exceptions
SQLException if an error occurs while processing the ResultSet.
Definition at line 77 of file BaseDTOHome.java.
                                                                                    {
        if (rs == null)
            return false;
        for (Map.Entry<String, DTOTypes> entry : dto.getFields().entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValueFromResultSet(rs, fieldName, fieldType);
            dto.setValue(fieldName, value);
        }
        return true;
    }
References getValueFromResultSet().
processLoadResult() [2/2]
Boolean BaseDTOHome.processLoadResult (ResultSet rs, List< IDTO > results) throws SQLException [protected]
Processes the load result from a ResultSet and populates a list of DTO objects.
Parameters
rs The ResultSet containing the data to be processed.
results The list of DTO objects to be populated.
Returns
true if the load result was processed successfully, false otherwise.
Exceptions
SQLException if an error occurs while processing the ResultSet.
Definition at line 56 of file BaseDTOHome.java.
                                                                                              {
        if (rs == null)
            return false;
        while (rs.next()) {
            IDTO dto = newDTOInstance();
            results.add(dto);
            processLoadResult(rs, dto);
        }
        return true;
    }
References newDTOInstance(), and processLoadResult().
Referenced by processLoadResult().
processSaveResult()
Boolean BaseDTOHome.processSaveResult (ResultSet rs, IDTO dto, List< IDTO > saveResults) throws SQLException [protected]
Processes the save result from the database and updates the DTO object accordingly.
Parameters
rs The ResultSet object containing the query result.
dto The DTO object to be updated.
saveResults The list of DTO objects that have been saved.
Returns
true if the save result was processed successfully, false otherwise.
Exceptions
SQLException if an error occurs while processing the save result.
Definition at line 198 of file BaseDTOHome.java.
                                                                                                            {
        if (rs == null)
            return false;
        for (Map.Entry<String, DTOTypes> entry : dto.getFields().entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValueFromResultSet(rs, fieldName, fieldType);
            dto.setValue(fieldName, value);
        }
        saveResults.add(dto);
        return true;
    }
References getValueFromResultSet().
queryDTOs()
List< IDTO > BaseDTOHome.queryDTOs (IDTO dtoQuery)
Queries the database for a list of DTOs based on the provided query DTO.
Parameters
dtoQuery the query DTO used to filter the results
Returns
a list of DTOs that match the query
Implements IDTOHome.
Definition at line 20 of file BaseDTOHome.java.
                                               {
        List<IDTO> dtos = new ArrayList<IDTO>();
        return dtos;
    }
saveDTO()
Boolean BaseDTOHome.saveDTO (IDTO dto)
Saves a single DTO object.
Parameters
dto The DTO object to be saved.
Returns
true if the DTO object is successfully saved, false otherwise.
Implements IDTOHome.
Definition at line 32 of file BaseDTOHome.java.
                                     {
        return this.saveDTOs(Arrays.asList(dto));
    }
References saveDTOs().
saveDTOs()
Boolean BaseDTOHome.saveDTOs (List< IDTO > dtos)
Saves a list of DTOs.
Parameters
dtos the list of DTOs to be saved
Returns
true if the DTOs are successfully saved, false otherwise
Implements IDTOHome.
Definition at line 43 of file BaseDTOHome.java.
                                             {
        return false;
    }
Referenced by saveDTO().
The documentation for this class was generated from the following file:
BaseDTOHome.java