ShoppingSystem Class Reference
The main class representing the shopping system.
Public Member Functions
WebServer getServer ()
ShoppingDataLayerService getShoppingDataService ()
ShoppingBusinessLayerService getShoppingBusinessService ()
ShoppingSystem (IEnvironment environment)
Constructs a new ShoppingSystem object with the specified environment.
void configure ()
Configures the shopping system by configuring the data service, business service, and web interface adapter.
void start ()
Starts the shopping system by configuring the data service, business service, web interface adapter, and starting the server.
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The logging agent used for logging application events.
WebServer server
Represents a web server for the shopping system.
IEnvironment environment
Represents the environment for the shopping system.
ShoppingDataLayerService shoppingDataService
Represents the service for accessing the data layer of the shopping system.
ShoppingBusinessLayerService shoppingBusinessService
Represents the business layer service for shopping operations.
ShoppingWebInterfaceAdapter shoppingWebInterfaceAdapter
This class represents an adapter for the shopping web interface.
Detailed Description
The main class representing the shopping system.
Definition at line 4 of file ShoppingSystem.java.
Constructor & Destructor Documentation
ShoppingSystem()
ShoppingSystem.ShoppingSystem (IEnvironment environment)
Constructs a new ShoppingSystem object with the specified environment.
Parameters
environment the environment in which the shopping system operates
Definition at line 64 of file ShoppingSystem.java.
                                                    {
        this.environment = environment;
        this.shoppingDataService = new ShoppingDataLayerService(this.environment);
        this.shoppingBusinessService = new ShoppingBusinessLayerService(this.environment, this.shoppingDataService);
        this.server = new WebServer();
        this.shoppingWebInterfaceAdapter = new ShoppingWebInterfaceAdapter(this.environment, this.shoppingDataService,
                this.shoppingBusinessService, this.server);
    }
References environment.
Member Function Documentation
configure()
void ShoppingSystem.configure ()
Configures the shopping system by configuring the data service, business service, and web interface adapter.
Definition at line 78 of file ShoppingSystem.java.
                            {
        this.shoppingDataService.configure();
        this.shoppingBusinessService.configure();
    }
References ShoppingBusinessLayerService.configure(), and ShoppingDataLayerService.configure().
Referenced by start().
getServer()
WebServer ShoppingSystem.getServer ()
Returns
the server
Definition at line 19 of file ShoppingSystem.java.
                                 {
        return server;
    }
References server.
getShoppingBusinessService()
ShoppingBusinessLayerService ShoppingSystem.getShoppingBusinessService ()
Returns
the shoppingBusinessService
Definition at line 48 of file ShoppingSystem.java.
                                                                     {
        return shoppingBusinessService;
    }
References shoppingBusinessService.
getShoppingDataService()
ShoppingDataLayerService ShoppingSystem.getShoppingDataService ()
Returns
the shoppingDataService
Definition at line 36 of file ShoppingSystem.java.
                                                             {
        return shoppingDataService;
    }
References shoppingDataService.
start()
void ShoppingSystem.start ()
Starts the shopping system by configuring the data service, business service, web interface adapter, and starting the server.
Definition at line 87 of file ShoppingSystem.java.
                        {
        this.configure();
        this.shoppingWebInterfaceAdapter.configure();
        this.server.start();
    }
References configure(), ShoppingWebInterfaceAdapter.configure(), and WebServer.start().
Referenced by MainClass.start().
Member Data Documentation
environment
IEnvironment ShoppingSystem.environment [private]
Represents the environment for the shopping system.
This interface provides methods to interact with the environment.
Definition at line 27 of file ShoppingSystem.java.
Referenced by ShoppingSystem().
logging
AppLoggingAgent ShoppingSystem.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
The logging agent used for logging application events.
Definition at line 9 of file ShoppingSystem.java.
server
WebServer ShoppingSystem.server [private]
Represents a web server for the shopping system.
Definition at line 14 of file ShoppingSystem.java.
Referenced by getServer().
shoppingBusinessService
ShoppingBusinessLayerService ShoppingSystem.shoppingBusinessService [private]
Represents the business layer service for shopping operations.
Definition at line 43 of file ShoppingSystem.java.
Referenced by getShoppingBusinessService().
shoppingDataService
ShoppingDataLayerService ShoppingSystem.shoppingDataService [private]
Represents the service for accessing the data layer of the shopping system.
Definition at line 31 of file ShoppingSystem.java.
Referenced by getShoppingDataService().
shoppingWebInterfaceAdapter
ShoppingWebInterfaceAdapter ShoppingSystem.shoppingWebInterfaceAdapter [private]
This class represents an adapter for the shopping web interface.
It is responsible for handling the communication between the shopping system and the web interface.
Definition at line 57 of file ShoppingSystem.java.
The documentation for this class was generated from the following file:
ShoppingSystem.java