ShoppingBusinessLayerService Class Reference
The ShoppingBusinessLayerService class represents the business layer service for shopping operations.
Public Member Functions
ShoppingDataLayerService getShoppingDataService ()
ShoppingPaymentService getShoppingPaymentService ()
ShoppingBusinessLayerService (IEnvironment environment, ShoppingDataLayerService shoppingDataService)
Constructs a ShoppingBusinessLayerService object with the specified environment and data layer service.
void configure ()
Configures the shopping business layer service.
UserDTO getUser (String username)
Retrieves the user information for the specified username.
IProductCatalog getProductCatalog ()
Retrieves the product catalog.
IDTO getProductById (Integer productId)
Retrieves a product by its ID.
IDTO getUser (Integer userId)
Retrieves the UserDTO object for the given user ID.
List< IDTO > getRoles ()
Retrieves a list of roles.
List< IDTO > getUserRoles (Integer userId)
Retrieves the roles associated with a user.
IDTO getActiveCart (Integer userId)
Retrieves the active cart for a given user.
List< IDTO > getPaymentProfiles ()
Retrieves a list of payment profiles.
IDTO getPaymentProfile (Integer paymentProfileId)
Retrieves the payment profile with the specified ID.
List< IDTO > getUserProfiles (Integer userId)
Retrieves the user profiles associated with the given user ID.
List< IDTO > getCartByStatus (Integer userId, String status)
Retrieves a list of cart items based on the user ID and status.
IDTO getCart (Integer cartId)
Retrieves the cart with the specified cart ID.
List< IDTO > getCartItems (Integer cartId)
Retrieves the list of cart items for a given cart ID.
IDTO getUserDTO (String email)
Retrieves the UserDTO object based on the provided email address.
IDTO getOrder (Integer orderId)
Boolean validateLogin (String user, String pwd)
Validates the login credentials for the specified user and password.
List< IDTO > saveDTO (IDTO dto)
Saves the given DTO object.
List< IDTO > loadDTOs (IDTO dto)
Loads a list of DTOs based on the given DTO object.
Protected Member Functions
void addAuditTrail (String msg, UserDTO userDTO)
Adds an audit trail entry with the specified message and user information.
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The logging agent used for logging in the shopping business layer service.
IEnvironment environment
The environment used by the ShoppingBusinessLayerService.
ShoppingDataLayerService shoppingDataService
The data layer service for shopping operations.
ShoppingPaymentService shoppingPaymentService
The shopping payment service used by the shopping business layer.
Detailed Description
The ShoppingBusinessLayerService class represents the business layer service for shopping operations.
It provides methods for configuring the service, retrieving user information, and validating login credentials.
Definition at line 9 of file ShoppingBusinessLayerService.java.
Constructor & Destructor Documentation
ShoppingBusinessLayerService()
ShoppingBusinessLayerService.ShoppingBusinessLayerService (IEnvironment environment, ShoppingDataLayerService shoppingDataService)
Constructs a ShoppingBusinessLayerService object with the specified environment and data layer service.
Parameters
environment The environment object used for configuration.
shoppingDataService The data layer service used for accessing shopping data.
Definition at line 51 of file ShoppingBusinessLayerService.java.
                                                                                                                {
        this.environment = environment;
        this.shoppingDataService = shoppingDataService;
        this.shoppingPaymentService = new ShoppingPaymentService(this.environment, this);
    }
References environment, and shoppingDataService.
Member Function Documentation
addAuditTrail()
void ShoppingBusinessLayerService.addAuditTrail (String msg, UserDTO userDTO) [protected]
Adds an audit trail entry with the specified message and user information.
Parameters
msg The message to be logged in the audit trail.
userDTO The UserDTO object representing the user associated with the action.
Definition at line 89 of file ShoppingBusinessLayerService.java.
                                                              {
        AuditTrailDTO auditTrailDTO = (AuditTrailDTO) AuditTrailDTOHome.Instance().newDTOInstance();
        auditTrailDTO.setValue("user_id", userDTO.getValue("id"));
        auditTrailDTO.setValue("action", msg);
        this.shoppingDataService.saveDTO(auditTrailDTO);
    }
References AuditTrailDTOHome.Instance(), and ShoppingDataLayerService.saveDTO().
Referenced by ShoppingPaymentService.processPayment(), saveDTO(), and validateLogin().
configure()
void ShoppingBusinessLayerService.configure ()
Configures the shopping business layer service.
Definition at line 61 of file ShoppingBusinessLayerService.java.
                            {
        this.shoppingPaymentService.configure();
    }
References ShoppingPaymentService.configure().
Referenced by ShoppingSystem.configure().
getActiveCart()
IDTO ShoppingBusinessLayerService.getActiveCart (Integer userId)
Retrieves the active cart for a given user.
Parameters
userId the ID of the user
Returns
a list of active cart items
Definition at line 164 of file ShoppingBusinessLayerService.java.
                                              {
        return this.getCartByStatus(userId, "active").getFirst();
    }
References getCartByStatus().
Referenced by TestZIntegration.testIntegration_AddToBasket(), and TestZIntegration.testIntegration_GetBasket().
getCart()
IDTO ShoppingBusinessLayerService.getCart (Integer cartId)
Retrieves the cart with the specified cart ID.
Parameters
cartId The ID of the cart to retrieve.
Returns
The cart with the specified ID, or an empty cart if no cart is found.
Definition at line 226 of file ShoppingBusinessLayerService.java.
                                        {
        CartDTO cart = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        cart.setValue("id", cartId);
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(cart, cart.getDtoHome());
        if (dtos.size() == 0)
            return cart;
        return (CartDTO) dtos.getFirst();
    }
References CartDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by ShoppingPaymentService.processPayment().
getCartByStatus()
List< IDTO > ShoppingBusinessLayerService.getCartByStatus (Integer userId, String status)
Retrieves a list of cart items based on the user ID and status.
Parameters
userId the ID of the user
status the status of the cart items
Returns
a list of cart items that match the given user ID and status
Definition at line 213 of file ShoppingBusinessLayerService.java.
                                                                     {
        CartDTO cart = (CartDTO) CartDTOHome.Instance().newDTOInstance();
        cart.setValue("user_id", userId);
        cart.setValue("status", status);
        return this.shoppingDataService.loadDTOs(cart, cart.getDtoHome());
    }
References CartDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by getActiveCart().
getCartItems()
List< IDTO > ShoppingBusinessLayerService.getCartItems (Integer cartId)
Retrieves the list of cart items for a given cart ID.
Parameters
cartId The ID of the cart.
Returns
The list of cart items.
Definition at line 241 of file ShoppingBusinessLayerService.java.
                                                   {
        CartItemDTO cartItem = (CartItemDTO) CartItemDTOHome.Instance().newDTOInstance();
        cartItem.setValue("cart_id", cartId);
        return this.shoppingDataService.loadDTOs(cartItem, cartItem.getDtoHome());
    }
References CartItemDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by ShoppingPaymentService.processPayment().
getOrder()
IDTO ShoppingBusinessLayerService.getOrder (Integer orderId)
Definition at line 263 of file ShoppingBusinessLayerService.java.
                                          {
        OrderDTO order = (OrderDTO) OrderDTOHome.Instance().newDTOInstance();
        order.setValue("id", orderId);
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(order, order.getDtoHome());
        if (dtos.size() == 0)
            return order;
        return (OrderDTO) dtos.getFirst();
    }
References OrderDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
getPaymentProfile()
IDTO ShoppingBusinessLayerService.getPaymentProfile (Integer paymentProfileId)
Retrieves the payment profile with the specified ID.
Parameters
paymentProfileId The ID of the payment profile to retrieve.
Returns
The payment profile with the specified ID, or a new instance of PaymentProfileDTO if no profile is found.
Definition at line 185 of file ShoppingBusinessLayerService.java.
                                                            {
        PaymentProfileDTO paymentProfile = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        paymentProfile.setValue("id", paymentProfileId);
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(paymentProfile, paymentProfile.getDtoHome());
        if (dtos.size() == 0)
            return paymentProfile;
        return (PaymentProfileDTO) dtos.getFirst();
    }
References PaymentProfileDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by ShoppingPaymentService.processPayment().
getPaymentProfiles()
List< IDTO > ShoppingBusinessLayerService.getPaymentProfiles ()
Retrieves a list of payment profiles.
Returns
A list of payment profiles.
Definition at line 173 of file ShoppingBusinessLayerService.java.
                                           {
        PaymentProfileDTO paymentProfile = (PaymentProfileDTO) PaymentProfileDTOHome.Instance().newDTOInstance();
        return this.shoppingDataService.loadDTOs(paymentProfile, paymentProfile.getDtoHome());
    }
References PaymentProfileDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
getProductById()
IDTO ShoppingBusinessLayerService.getProductById (Integer productId)
Retrieves a product by its ID.
Parameters
productId The ID of the product to retrieve.
Returns
The product with the specified ID, or an empty product if not found.
Definition at line 113 of file ShoppingBusinessLayerService.java.
                                                  {
        ProductDTO product = (ProductDTO) ProductDTOHome.Instance().newDTOInstance();
        product.setValue("id", productId);
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(product, product.getDtoHome());
        if (dtos.size() == 0)
            return product;
        return (ProductDTO) dtos.getFirst();
    }
References ProductDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by ShoppingPaymentService.processPayment().
getProductCatalog()
IProductCatalog ShoppingBusinessLayerService.getProductCatalog ()
Retrieves the product catalog.
Returns
The product catalog.
Definition at line 101 of file ShoppingBusinessLayerService.java.
                                               {
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(ProductDTOHome.Instance().newDTOInstance(),
                ProductDTOHome.Instance());
        return new ProductCatalog(dtos);
    }
References ProductDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by TestZIntegration.testIntegration_AddToBasket(), and TestZIntegration.testIntegration_GetProductCatalog().
getRoles()
List< IDTO > ShoppingBusinessLayerService.getRoles ()
Retrieves a list of roles.
Returns
A list of IDTO objects representing the roles.
Definition at line 142 of file ShoppingBusinessLayerService.java.
                                 {
        return this.shoppingDataService.loadDTOs(RoleDTOHome.Instance().newDTOInstance(), RoleDTOHome.Instance());
    }
References RoleDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
getShoppingDataService()
ShoppingDataLayerService ShoppingBusinessLayerService.getShoppingDataService ()
Returns
the shoppingDataService
Definition at line 27 of file ShoppingBusinessLayerService.java.
                                                             {
        return shoppingDataService;
    }
References shoppingDataService.
getShoppingPaymentService()
ShoppingPaymentService ShoppingBusinessLayerService.getShoppingPaymentService ()
Returns
the shoppingPaymentService
Definition at line 39 of file ShoppingBusinessLayerService.java.
                                                              {
        return shoppingPaymentService;
    }
References shoppingPaymentService.
Referenced by TestZIntegration.testIntegration_AddToBasket().
getUser() [1/2]
IDTO ShoppingBusinessLayerService.getUser (Integer userId)
Retrieves the UserDTO object for the given user ID.
Parameters
userId The ID of the user.
Returns
The UserDTO object representing the user.
Definition at line 128 of file ShoppingBusinessLayerService.java.
                                        {
        UserDTO user = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        user.setValue("id", userId);
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(user, user.getDtoHome());
        if (dtos.size() == 0)
            return user;
        return (UserDTO) dtos.getFirst();
    }
References UserDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
getUser() [2/2]
UserDTO ShoppingBusinessLayerService.getUser (String username)
Retrieves the user information for the specified username.
Parameters
username The username of the user.
Returns
The UserDTO object representing the user information.
Definition at line 71 of file ShoppingBusinessLayerService.java.
                                            {
        UserDTO user = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        user.setValue("email_address", username);
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(user, user.getDtoHome());
        if (dtos.size() == 0)
            return user;
        return (UserDTO) dtos.getFirst();
    }
References UserDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by ShoppingPaymentService.processPayment(), TestZIntegration.testIntegration_AddToBasket(), TestZIntegration.testIntegration_GetBasket(), and validateLogin().
getUserDTO()
IDTO ShoppingBusinessLayerService.getUserDTO (String email)
Retrieves the UserDTO object based on the provided email address.
Parameters
email The email address of the user.
Returns
The UserDTO object representing the user with the provided email address.
Definition at line 254 of file ShoppingBusinessLayerService.java.
                                         {
        UserDTO user = (UserDTO) UserDTOHome.Instance().newDTOInstance();
        user.setValue("email_address", email);
        List<IDTO> dtos = this.shoppingDataService.loadDTOs(user, user.getDtoHome());
        if (dtos.size() == 0)
            return user;
        return (UserDTO) dtos.getFirst();
    }
References UserDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
getUserProfiles()
List< IDTO > ShoppingBusinessLayerService.getUserProfiles (Integer userId)
Retrieves the user profiles associated with the given user ID.
Parameters
userId The ID of the user.
Returns
A list of user profiles.
Definition at line 200 of file ShoppingBusinessLayerService.java.
                                                      {
        UserProfileDTO userProfile = (UserProfileDTO) UserProfileDTOHome.Instance().newDTOInstance();
        userProfile.setValue("user_id", userId);
        return this.shoppingDataService.loadDTOs(userProfile, userProfile.getDtoHome());
    }
References UserProfileDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
Referenced by TestZIntegration.testIntegration_AddToBasket().
getUserRoles()
List< IDTO > ShoppingBusinessLayerService.getUserRoles (Integer userId)
Retrieves the roles associated with a user.
Parameters
userId The ID of the user.
Returns
A list of IDTO objects representing the user roles.
Definition at line 152 of file ShoppingBusinessLayerService.java.
                                                   {
        UserRoleDTO userRole = (UserRoleDTO) UserRoleDTOHome.Instance().newDTOInstance();
        userRole.setValue("user_id", userId);
        return this.shoppingDataService.loadDTOs(userRole, userRole.getDtoHome());
    }
References UserRoleDTOHome.Instance(), and ShoppingDataLayerService.loadDTOs().
loadDTOs()
List< IDTO > ShoppingBusinessLayerService.loadDTOs (IDTO dto)
Loads a list of DTOs based on the given DTO object.
Parameters
dto The DTO object used to load the DTOs.
Returns
A list of IDTO objects representing the loaded DTOs.
Definition at line 316 of file ShoppingBusinessLayerService.java.
                                         {
        return this.shoppingDataService.loadDTOs(dto, dto.getDtoHome());
    }
References ShoppingDataLayerService.loadDTOs().
saveDTO()
List< IDTO > ShoppingBusinessLayerService.saveDTO (IDTO dto)
Saves the given DTO object.
Parameters
dto The DTO object to be saved.
Returns
The list of saved DTO objects.
Definition at line 305 of file ShoppingBusinessLayerService.java.
                                        {
        this.addAuditTrail("saving record: " + dto.getDtoName(), (UserDTO) UserDTOHome.Instance().newDTOInstance());
        return this.shoppingDataService.saveDTO(dto);
    }
References addAuditTrail(), IDTO.getDtoName(), UserDTOHome.Instance(), and ShoppingDataLayerService.saveDTO().
Referenced by ShoppingPaymentService.processPayment(), and TestZIntegration.testIntegration_AddToBasket().
validateLogin()
Boolean ShoppingBusinessLayerService.validateLogin (String user, String pwd)
Validates the login credentials for the specified user and password.
Parameters
user The username.
pwd The password.
Returns
true if the login credentials are valid, false otherwise.
Definition at line 279 of file ShoppingBusinessLayerService.java.
                                                          {
        String inputPwdHash = CoreUtils.encodeSha256String(pwd);
        UserDTO userDTO = getUser(user);
        String userName = userDTO.getValue("email_address").toString();
        if (userName == null) {
            String msg = "Login attempt for user: " + user + " with password: " + inputPwdHash + " - Unknown User";
            addAuditTrail(msg, userDTO);
            return false;
        }
        String passwordHash = userDTO.getValue("password_hash").toString();
        Boolean isValid = user.equals(userName) && inputPwdHash.equals(passwordHash);
        String msg = "Login attempt for user: " + user + " with password: " + inputPwdHash + " - "
                + (isValid ? "Success" : "Failure");
        addAuditTrail(msg, userDTO);
        return isValid;
    }
References addAuditTrail(), CoreUtils.encodeSha256String(), and getUser().
Referenced by ShoppingWebInterfaceController.validateLogin().
Member Data Documentation
environment
IEnvironment ShoppingBusinessLayerService.environment [private]
The environment used by the ShoppingBusinessLayerService.
Definition at line 18 of file ShoppingBusinessLayerService.java.
Referenced by ShoppingBusinessLayerService().
logging
AppLoggingAgent ShoppingBusinessLayerService.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
The logging agent used for logging in the shopping business layer service.
Definition at line 14 of file ShoppingBusinessLayerService.java.
shoppingDataService
ShoppingDataLayerService ShoppingBusinessLayerService.shoppingDataService [private]
The data layer service for shopping operations.
Definition at line 22 of file ShoppingBusinessLayerService.java.
Referenced by getShoppingDataService(), and ShoppingBusinessLayerService().
shoppingPaymentService
ShoppingPaymentService ShoppingBusinessLayerService.shoppingPaymentService [private]
The shopping payment service used by the shopping business layer.
Definition at line 34 of file ShoppingBusinessLayerService.java.
Referenced by getShoppingPaymentService().
The documentation for this class was generated from the following file:
ShoppingBusinessLayerService.java