Environment Class Reference
The Environment class represents the environment in which the application is running.
Public Member Functions
String[] getComnandLineArgs ()
Returns the command line arguments passed to the application.
String getValue (String key)
Retrieves the value associated with the specified key from the properties.
List< String > getKeys ()
Returns a list of keys in the environment.
Boolean HasKey (String key)
Checks if the specified key exists in the environment.
Static Public Member Functions
static IEnvironment Instance ()
Represents an interface for the environment.
Private Member Functions
Environment (String[] args)
The Environment class represents the environment settings for the shopping system.
Static Private Member Functions
static IEnvironment getInstance ()
Represents an environment.
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The logging agent used for logging application events.
Properties _properties = new Properties(System.getProperties())
The properties for the environment.
String[] args
The command line arguments passed to the program.
Static Private Attributes
static IEnvironment _instance = getInstance()
Detailed Description
The Environment class represents the environment in which the application is running.
It provides access to command line arguments, properties, and other environment-related information.
Definition at line 11 of file Environment.java.
Constructor & Destructor Documentation
Environment()
Environment.Environment (String[] args) [private]
The Environment class represents the environment settings for the shopping system.
It loads the properties from a file and provides access to them through the _properties map.
Definition at line 47 of file Environment.java.
                                       {
        this.args = args;
        String filename = System.getProperty("PROPERTY_FILE_NAME", "app.properties");
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(filename)) {
            Properties prop = new Properties();
            // is stream valid?
            if (input == null) {
                logging.log("Error finding " + filename);
                return;
            }
            // load a properties file from class path
            prop.load(input);
            // overlay properties from file
            prop.forEach((key, value) -> _properties.put(key, value));
            _properties.put("PROPERTY_FILE_NAME", filename);
        } catch (IOException ex) {
            logging.log(ex.getMessage(), ex);
        }
    }
References _properties, args, AppLoggingAgent.log(), and logging.
Member Function Documentation
getComnandLineArgs()
String[] Environment.getComnandLineArgs ()
Returns the command line arguments passed to the application.
Returns
an array of strings representing the command line arguments
Implements IEnvironment.
Definition at line 76 of file Environment.java.
                                         {
        return this.args;
    }
References args.
getInstance()
static IEnvironment Environment.getInstance () [static], [private]
Represents an environment.
Definition at line 18 of file Environment.java.
                                              {
        return new Environment(ProcessHandle.current().info().arguments().orElse(new String[0]));
    }
getKeys()
List< String > Environment.getKeys ()
Returns a list of keys in the environment.
Returns
a list of keys
Implements IEnvironment.
Definition at line 97 of file Environment.java.
                                  {
        List<String> keys = new ArrayList<String>();
        _properties.forEach((key, value) -> keys.add((String) key));
        return keys;
    }
References _properties.
getValue()
String Environment.getValue (String key)
Retrieves the value associated with the specified key from the properties.
Parameters
key the key whose associated value is to be retrieved
Returns
the value to which the specified key is mapped, or null if the key is not found
Implements IEnvironment.
Definition at line 87 of file Environment.java.
                                       {
        return _properties.getProperty(key, null);
    }
References _properties.
HasKey()
Boolean Environment.HasKey (String key)
Checks if the specified key exists in the environment.
Parameters
key the key to check
Returns
true if the key exists, false otherwise
Implements IEnvironment.
Definition at line 110 of file Environment.java.
                                      {
        return _properties.containsKey(key);
    }
References _properties.
Instance()
static IEnvironment Environment.Instance () [static]
Represents an interface for the environment.
Definition at line 25 of file Environment.java.
                                          {
        return _instance;
    }
References _instance.
Referenced by MainClass.start(), TestDTO.testCartDTO_1(), TestDTO.testCartDTO_2(), TestDTO.testCartItemDTO_1(), TestDTO.testCartItemDTO_2(), TestDTO.testOrderDTO_1(), TestDTO.testOrderDTO_2(), TestDTO.testOrderItemDTO_1(), TestDTO.testPaymentProfileDTO_1(), TestDTO.testPaymentProfileDTO_2(), TestDTO.testProductDTO_1(), TestDTO.testProductDTO_2(), TestDTO.testProductDTO_3(), TestDTO.testProductDTO_4(), TestDTO.testPurchaseDTO_1(), TestDTO.testPurchaseDTO_2(), TestDTO.testRoleDTO_1(), TestDTO.testRoleDTO_2(), TestDTO.testUserDTO_1(), TestDTO.testUserDTO_2(), TestDTO.testUserDTO_3(), TestDTO.testUserProfileDTO_1(), TestDTO.testUserProfileDTO_2(), TestDTO.testUserRoleDTO_1(), and TestDTO.testUserRoleDTO_2().
Member Data Documentation
_instance
IEnvironment Environment._instance = getInstance() [static], [private]
Definition at line 13 of file Environment.java.
Referenced by Instance().
_properties
Properties Environment._properties = new Properties(System.getProperties()) [private]
The properties for the environment.
Definition at line 36 of file Environment.java.
Referenced by Environment(), getKeys(), getValue(), and HasKey().
args
String [] Environment.args [private]
The command line arguments passed to the program.
Definition at line 41 of file Environment.java.
Referenced by Environment(), and getComnandLineArgs().
logging
AppLoggingAgent Environment.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
The logging agent used for logging application events.
Definition at line 32 of file Environment.java.
Referenced by Environment().
The documentation for this class was generated from the following file:
Environment.java