DbBaseFactoryWrapper Class Reference
The class is a factory for creating instances of the IDbConnectionWrapper interface.
Public Member Functions
String getUsername ()
The function returns the username for the database.
void setUsername (String username)
The function sets the username for the database.
String getPassword ()
The function returns the password for the database.
void setPassword (String password)
The function sets the password for the database.
String getHost ()
The function returns the host for the database.
void setHost (String host)
The function sets the host for the database.
String getDatabase ()
The function returns the database name.
void setDatabase (String database)
The function sets the database name.
int getPort ()
The function returns the port for the database.
void setPort (int port)
The function sets the port for the database.
String getUrl ()
The function returns the url for the database.
void setUrl (String url)
The function sets the url for the database.
String getSchema ()
void setSchema (String schema)
DbBaseFactoryWrapper ()
void connectionProperties (String user, String pass, int port, String host, String database, String schema)
The function sets the connection properties.
abstract String buildJdbcUrl ()
The function builds the jdbc url for the database.
void close () throws IOException
The function closes the connection to the database.
Boolean query (String query, IDbResultProcessor resultProcessor)
Executes the given query on the database and processes the result using the provided IDbResultProcessor.
Boolean execute (String query, IDbResultProcessor resultProcessor)
Executes the given query and processes the result using the provided IDbResultProcessor.
Static Protected Attributes
static AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The function returns an instance of the AppLoggingAgent class.
Private Attributes
String username
String password
String host
String database
int port
String url
String schema
Additional Inherited Members
Static Public Member Functions inherited from IFactory< IDbConnectionWrapper >
static< T > void register (String registrationName, Class< T > instance)
The function registers a class with the factory.
static< T > T create (String factoryString)
The function returns an instance of the IFactory class.
static< T > String convertUrlToString (final InputStream input, final String string) throws IOException
The function converts the content of an InputStream into a String using the specified character encoding.
static String[] getRegistered ()
The function returns an array of strings representing the names of the registered classes.
static< T > IFactory< T > Instance ()
The function returns an instance of the IFactory class.
Protected Member Functions inherited from IFactory< IDbConnectionWrapper >
IFactory ()
The function returns an instance of the IFactory class.
Static Package Functions inherited from IFactory< IDbConnectionWrapper >
[static initializer]
Detailed Description
The class is a factory for creating instances of the IDbConnectionWrapper interface.
Definition at line 12 of file DbBaseFactoryWrapper.java.
Constructor & Destructor Documentation
DbBaseFactoryWrapper()
DbBaseFactoryWrapper.DbBaseFactoryWrapper ()
Definition at line 156 of file DbBaseFactoryWrapper.java.
                                  {
    }
Member Function Documentation
buildJdbcUrl()
abstract String DbBaseFactoryWrapper.buildJdbcUrl () [abstract]
The function builds the jdbc url for the database.
Returns
The method is returning the jdbc url for the database.
Reimplemented in DbBaseFactoryWrapper_postgres.
Referenced by connectionProperties().
close()
void DbBaseFactoryWrapper.close () throws IOException
The function closes the connection to the database.
Exceptions
IOException
Implements IDbConnectionWrapper.
Definition at line 194 of file DbBaseFactoryWrapper.java.
                                           {
        logging.log(this.getClass().getName() + " closed");
    }
References AppLoggingAgent.log(), and logging.
connectionProperties()
void DbBaseFactoryWrapper.connectionProperties (String user, String pass, int port, String host, String database, String schema)
The function sets the connection properties.
Parameters
user The username for the database.
pass The password for the database.
port The port for the database.
host The host for the database.
database The database name.
schema The schema name.
Implements IDbConnectionWrapper.
Definition at line 169 of file DbBaseFactoryWrapper.java.
                                                                                                                      {
        this.username = user;
        this.password = pass;
        this.port = port;
        this.host = host;
        this.database = database;
        this.schema = schema;
        this.url = buildJdbcUrl();
        logging.log("URL: " + this.url);
    }
References buildJdbcUrl(), database, host, AppLoggingAgent.log(), logging, port, and schema.
execute()
Boolean DbBaseFactoryWrapper.execute (String query, IDbResultProcessor resultProcessor)
Executes the given query and processes the result using the provided IDbResultProcessor.
Parameters
query the SQL query to execute
resultProcessor the IDbResultProcessor to process the result
Returns
the execution status of the query as a Boolean
Implements IDbConnectionWrapper.
Definition at line 234 of file DbBaseFactoryWrapper.java.
                                                                             {
        logging.log("username: " + username);
        logging.log("password: " + password.length());
        logging.log("query: " + query);
        try (Connection con = DriverManager.getConnection(
                url, this.username, this.password)) {
            Statement stmt = con.createStatement();
            Boolean status = stmt.execute(query);
            logging.log("query execute status: " + status);
            if (status) {
                ResultSet rs = stmt.getResultSet();
                return resultProcessor.process(rs);
            }
            return true;
        } catch (SQLException e) {
            logging.log(e);
        }
        // logging.log(response);
        return false;
    }
References AppLoggingAgent.log(), logging, password, IDbResultProcessor.process(), query(), url, and username.
getDatabase()
String DbBaseFactoryWrapper.getDatabase ()
The function returns the database name.
Returns
The method is returning the database name.
Definition at line 87 of file DbBaseFactoryWrapper.java.
                                {
        return database;
    }
References database.
Referenced by DbBaseFactoryWrapper_postgres.buildJdbcUrl().
getHost()
String DbBaseFactoryWrapper.getHost ()
The function returns the host for the database.
Returns
The method is returning the host for the database.
Definition at line 67 of file DbBaseFactoryWrapper.java.
                            {
        return host;
    }
References host.
Referenced by DbBaseFactoryWrapper_postgres.buildJdbcUrl().
getPassword()
String DbBaseFactoryWrapper.getPassword ()
The function returns the password for the database.
Returns
The method is returning the password for the database.
Definition at line 47 of file DbBaseFactoryWrapper.java.
                                {
        return password;
    }
References password.
getPort()
int DbBaseFactoryWrapper.getPort ()
The function returns the port for the database.
Returns
The method is returning the port for the database.
Definition at line 107 of file DbBaseFactoryWrapper.java.
                         {
        return port;
    }
References port.
Referenced by DbBaseFactoryWrapper_postgres.buildJdbcUrl().
getSchema()
String DbBaseFactoryWrapper.getSchema ()
Returns
the schema
Definition at line 145 of file DbBaseFactoryWrapper.java.
                              {
        return schema;
    }
References schema.
getUrl()
String DbBaseFactoryWrapper.getUrl ()
The function returns the url for the database.
Returns
The method is returning the url for the database.
Definition at line 127 of file DbBaseFactoryWrapper.java.
                           {
        return url;
    }
References url.
getUsername()
String DbBaseFactoryWrapper.getUsername ()
The function returns the username for the database.
Returns
The method is returning the username for the database.
Definition at line 27 of file DbBaseFactoryWrapper.java.
                                {
        return username;
    }
References username.
query()
Boolean DbBaseFactoryWrapper.query (String query, IDbResultProcessor resultProcessor)
Executes the given query on the database and processes the result using the provided IDbResultProcessor.
Parameters
query The SQL query to be executed.
resultProcessor The IDbResultProcessor implementation to process the query result.
Returns
true if the query was executed successfully, false otherwise.
Implements IDbConnectionWrapper.
Definition at line 207 of file DbBaseFactoryWrapper.java.
                                                                           {
        logging.log("username: " + username);
        logging.log("password: " + password.length());
        logging.log("query: " + query);
        try (Connection con = DriverManager.getConnection(
                url, this.username, this.password)) {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            return resultProcessor.process(rs);
        } catch (SQLException e) {
            logging.log(e);
        }
        // logging.log(response);
        return false;
    }
References AppLoggingAgent.log(), logging, password, IDbResultProcessor.process(), query(), url, and username.
Referenced by execute(), and query().
setDatabase()
void DbBaseFactoryWrapper.setDatabase (String database)
The function sets the database name.
Parameters
database The database name.
Definition at line 96 of file DbBaseFactoryWrapper.java.
                                             {
        this.database = database;
    }
References database.
setHost()
void DbBaseFactoryWrapper.setHost (String host)
The function sets the host for the database.
Parameters
host The host for the database.
Definition at line 76 of file DbBaseFactoryWrapper.java.
                                     {
        this.host = host;
    }
References host.
setPassword()
void DbBaseFactoryWrapper.setPassword (String password)
The function sets the password for the database.
Parameters
password The password for the database.
Definition at line 56 of file DbBaseFactoryWrapper.java.
                                             {
        this.password = password;
    }
References password.
setPort()
void DbBaseFactoryWrapper.setPort (int port)
The function sets the port for the database.
Parameters
port The port for the database.
Definition at line 116 of file DbBaseFactoryWrapper.java.
                                  {
        this.port = port;
    }
References port.
setSchema()
void DbBaseFactoryWrapper.setSchema (String schema)
Parameters
schema the schema to set
Definition at line 152 of file DbBaseFactoryWrapper.java.
                                         {
        this.schema = schema;
    }
References schema.
setUrl()
void DbBaseFactoryWrapper.setUrl (String url)
The function sets the url for the database.
Parameters
url The url for the database.
Definition at line 136 of file DbBaseFactoryWrapper.java.
                                   {
        this.url = url;
    }
References url.
setUsername()
void DbBaseFactoryWrapper.setUsername (String username)
The function sets the username for the database.
Parameters
username The username for the database.
Definition at line 36 of file DbBaseFactoryWrapper.java.
                                             {
        this.username = username;
    }
References username.
Member Data Documentation
database
String DbBaseFactoryWrapper.database [private]
Definition at line 80 of file DbBaseFactoryWrapper.java.
Referenced by connectionProperties(), getDatabase(), and setDatabase().
host
String DbBaseFactoryWrapper.host [private]
Definition at line 60 of file DbBaseFactoryWrapper.java.
Referenced by connectionProperties(), getHost(), and setHost().
logging
AppLoggingAgent DbBaseFactoryWrapper.logging = new AppLoggingAgent(new AppLoggingStream()) [static], [protected]
The function returns an instance of the AppLoggingAgent class.
Returns
The method is returning an instance of the AppLoggingAgent class.
Definition at line 18 of file DbBaseFactoryWrapper.java.
Referenced by close(), connectionProperties(), DbBaseFactoryWrapper_postgres.DbBaseFactoryWrapper_postgres(), execute(), and query().
password
String DbBaseFactoryWrapper.password [private]
Definition at line 40 of file DbBaseFactoryWrapper.java.
Referenced by execute(), getPassword(), query(), and setPassword().
port
int DbBaseFactoryWrapper.port [private]
Definition at line 100 of file DbBaseFactoryWrapper.java.
Referenced by connectionProperties(), getPort(), and setPort().
schema
String DbBaseFactoryWrapper.schema [private]
Definition at line 140 of file DbBaseFactoryWrapper.java.
Referenced by connectionProperties(), getSchema(), and setSchema().
url
String DbBaseFactoryWrapper.url [private]
Definition at line 120 of file DbBaseFactoryWrapper.java.
Referenced by execute(), getUrl(), query(), and setUrl().
username
String DbBaseFactoryWrapper.username [private]
Definition at line 20 of file DbBaseFactoryWrapper.java.
Referenced by execute(), getUsername(), query(), and setUsername().
The documentation for this class was generated from the following file:
DbBaseFactoryWrapper.java