CartDTOHome Class Reference
This class represents a home for CartDTO objects.
Public Member Functions
IDTO newDTOInstance ()
Creates a new instance of CartDTO.
Public Member Functions inherited from BaseDTOHome
List< IDTO > queryDTOs (IDTO dtoQuery)
Queries the database for a list of DTOs based on the provided query DTO.
Boolean saveDTO (IDTO dto)
Saves a single DTO object.
Boolean saveDTOs (List< IDTO > dtos)
Saves a list of DTOs.
IDbResultProcessor getLoadProcessor ()
Gets the result processor for loading data from the database.
String getLoadSql (IDTO dto)
Returns the SQL query for loading data from the database based on the provided DTO object.
IDbResultProcessor getSaveProcessor (IDTO dto)
The function returns an instance of a class that implements the IDbResultProcessor interface, which processes the result set from a database save operation and returns a list of DTO objects.
String getSaveSql (IDTO dto)
Returns the SQL statement for saving the given DTO.
Static Public Member Functions
static IDTOHome Instance ()
Returns the singleton instance of CartDTOHome.
Private Member Functions
CartDTOHome ()
Static Private Attributes
static CartDTOHome instance = new CartDTOHome()
Additional Inherited Members
Protected Member Functions inherited from BaseDTOHome
Boolean processLoadResult (ResultSet rs, List< IDTO > results) throws SQLException
Processes the load result from a ResultSet and populates a list of DTO objects.
Boolean processLoadResult (ResultSet rs, IDTO dto) throws SQLException
Processes the load result from a ResultSet and sets the values in the given DTO.
Object getValueFromResultSet (ResultSet rs, String fieldName, DTOTypes dtoTypes) throws SQLException
Retrieves the value from the ResultSet based on the field name and data type.
String formatValueForQuery (Object value, DTOTypes dtoTypes)
Formats the given value for query based on the specified DTO type.
Boolean processSaveResult (ResultSet rs, IDTO dto, List< IDTO > saveResults) throws SQLException
Processes the save result from the database and updates the DTO object accordingly.
void buildInsertSql (StringBuilder sb, IDTO dto)
Builds the SQL query for inserting data into the database table.
void buildUpdateSql (StringBuilder sb, IDTO dto)
Builds an SQL update statement for the given DTO object.
Detailed Description
This class represents a home for CartDTO objects.
It extends the BaseDTOHome class and implements the IDTOHome interface. It provides methods for creating new instances of CartDTO objects.
Definition at line 7 of file CartDTOHome.java.
Constructor & Destructor Documentation
CartDTOHome()
CartDTOHome.CartDTOHome () [private]
Definition at line 11 of file CartDTOHome.java.
                          {
    }
Member Function Documentation
Instance()
static IDTOHome CartDTOHome.Instance () [static]
Returns the singleton instance of CartDTOHome.
Returns
the singleton instance of CartDTOHome
Definition at line 19 of file CartDTOHome.java.
                                      {
        return instance;
    }
References instance.
Referenced by CartDTO.getDtoHome(), TestDTO.testCartDTO_1(), TestDTO.testCartDTO_2(), TestDTO.testCartItemDTO_1(), TestDTO.testCartItemDTO_2(), TestDTO.testOrderDTO_1(), TestDTO.testOrderDTO_2(), and TestDTO.testOrderItemDTO_1().
newDTOInstance()
IDTO CartDTOHome.newDTOInstance ()
Creates a new instance of CartDTO.
Returns
a new instance of CartDTO
Reimplemented from BaseDTOHome.
Definition at line 28 of file CartDTOHome.java.
                                 {
        return new CartDTO();
    }
Member Data Documentation
instance
CartDTOHome CartDTOHome.instance = new CartDTOHome() [static], [private]
Definition at line 9 of file CartDTOHome.java.
Referenced by Instance().
The documentation for this class was generated from the following file:
CartDTOHome.java