ShoppingWebInterfaceController Class Reference
The ShoppingWebInterfaceController class represents a controller for the shopping web interface.
Public Member Functions
ShoppingWebInterfaceController (IEnvironment environment, ShoppingDataLayerService shoppingDataService, ShoppingBusinessLayerService shoppingBusinessService, WebServer server)
void configure ()
Configures the shopping web interface controller.
IEnvironment getEnvironment ()
Returns the environment object.
ShoppingDataLayerService getShoppingDataService ()
Returns the ShoppingDataLayerService instance used by this controller.
ShoppingBusinessLayerService getShoppingBusinessService ()
Returns the ShoppingBusinessLayerService instance used by this controller.
WebServer getServer ()
Returns the WebServer object associated with this controller.
Boolean validateLogin (String user, String pwd)
Validates the login credentials of a user.
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The logging agent used for logging events in the shopping web interface controller.
IEnvironment environment
The environment object used by the ShoppingWebInterfaceController.
ShoppingDataLayerService shoppingDataService
The shopping data service used by the shopping web interface controller.
ShoppingBusinessLayerService shoppingBusinessService
The shopping business layer service used by the web interface controller.
WebServer server
The web server used by the shopping web interface controller.
ShoppingWebAuthenticator authenticator
Detailed Description
The ShoppingWebInterfaceController class represents a controller for the shopping web interface.
It handles the configuration of routes and provides access to the environment, data layer service, business layer service, and web server.
Definition at line 9 of file ShoppingWebInterfaceController.java.
Constructor & Destructor Documentation
ShoppingWebInterfaceController()
ShoppingWebInterfaceController.ShoppingWebInterfaceController (IEnvironment environment, ShoppingDataLayerService shoppingDataService, ShoppingBusinessLayerService shoppingBusinessService, WebServer server)
Definition at line 35 of file ShoppingWebInterfaceController.java.
                                                                                    {
        this.environment = environment;
        this.shoppingDataService = shoppingDataService;
        this.shoppingBusinessService = shoppingBusinessService;
        this.server = server;
        this.authenticator = new ShoppingWebAuthenticator(this);
    }
References environment, server, shoppingBusinessService, and shoppingDataService.
Member Function Documentation
configure()
void ShoppingWebInterfaceController.configure ()
Configures the shopping web interface controller.
Adds a route for "/echo/" with the EchoHandler.
Definition at line 48 of file ShoppingWebInterfaceController.java.
                            {
        this.server.addRoute("/echo/", new EchoHandler(), this.authenticator);
    }
References WebServer.addRoute().
Referenced by ShoppingWebInterfaceAdapter.configure().
getEnvironment()
IEnvironment ShoppingWebInterfaceController.getEnvironment ()
Returns the environment object.
Returns
the environment object
Definition at line 57 of file ShoppingWebInterfaceController.java.
                                         {
        return this.environment;
    }
References environment.
getServer()
WebServer ShoppingWebInterfaceController.getServer ()
Returns the WebServer object associated with this controller.
Returns
the WebServer object
Definition at line 84 of file ShoppingWebInterfaceController.java.
                                 {
        return this.server;
    }
References server.
getShoppingBusinessService()
ShoppingBusinessLayerService ShoppingWebInterfaceController.getShoppingBusinessService ()
Returns the ShoppingBusinessLayerService instance used by this controller.
Returns
the ShoppingBusinessLayerService instance
Definition at line 75 of file ShoppingWebInterfaceController.java.
                                                                     {
        return this.shoppingBusinessService;
    }
References shoppingBusinessService.
getShoppingDataService()
ShoppingDataLayerService ShoppingWebInterfaceController.getShoppingDataService ()
Returns the ShoppingDataLayerService instance used by this controller.
Returns
the ShoppingDataLayerService instance
Definition at line 66 of file ShoppingWebInterfaceController.java.
                                                             {
        return this.shoppingDataService;
    }
References shoppingDataService.
validateLogin()
Boolean ShoppingWebInterfaceController.validateLogin (String user, String pwd)
Validates the login credentials of a user.
Parameters
user The username of the user.
pwd The password of the user.
Returns
true if the login credentials are valid, false otherwise.
Definition at line 95 of file ShoppingWebInterfaceController.java.
                                                          {
        return this.shoppingBusinessService.validateLogin(user, pwd);
    }
References ShoppingBusinessLayerService.validateLogin().
Referenced by ShoppingWebAuthenticator.checkCredentials().
Member Data Documentation
authenticator
ShoppingWebAuthenticator ShoppingWebInterfaceController.authenticator [private]
Definition at line 33 of file ShoppingWebInterfaceController.java.
environment
IEnvironment ShoppingWebInterfaceController.environment [private]
The environment object used by the ShoppingWebInterfaceController.
Definition at line 19 of file ShoppingWebInterfaceController.java.
Referenced by getEnvironment(), and ShoppingWebInterfaceController().
logging
AppLoggingAgent ShoppingWebInterfaceController.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
The logging agent used for logging events in the shopping web interface controller.
Definition at line 14 of file ShoppingWebInterfaceController.java.
server
WebServer ShoppingWebInterfaceController.server [private]
The web server used by the shopping web interface controller.
Definition at line 31 of file ShoppingWebInterfaceController.java.
Referenced by getServer(), and ShoppingWebInterfaceController().
shoppingBusinessService
ShoppingBusinessLayerService ShoppingWebInterfaceController.shoppingBusinessService [private]
The shopping business layer service used by the web interface controller.
Definition at line 27 of file ShoppingWebInterfaceController.java.
Referenced by getShoppingBusinessService(), and ShoppingWebInterfaceController().
shoppingDataService
ShoppingDataLayerService ShoppingWebInterfaceController.shoppingDataService [private]
The shopping data service used by the shopping web interface controller.
Definition at line 23 of file ShoppingWebInterfaceController.java.
Referenced by getShoppingDataService(), and ShoppingWebInterfaceController().
The documentation for this class was generated from the following file:
ShoppingWebInterfaceController.java