TestZIntegration Class Reference
Package Functions
void testIntegration_GetProductCatalog ()
void testIntegration_GetBasket ()
void testIntegration_AddToBasket ()
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
Detailed Description
Definition at line 14 of file TestZIntegration.java.
Member Function Documentation
testIntegration_AddToBasket()
void TestZIntegration.testIntegration_AddToBasket () [package]
Definition at line 62 of file TestZIntegration.java.
                                       {
        // get catalog
        ShoppingSystem system = new ShoppingSystem(Environment.Instance());
        system.configure();
        ShoppingBusinessLayerService shoppingBusinessService = system.getShoppingBusinessService();
        UserDTO user = shoppingBusinessService.getUser("joesample");
        logging.log(user.toString());
        assertNotNull(user.getValue("id"));
        IDTO basket = shoppingBusinessService.getActiveCart((Integer) user.getValue("id"));
        logging.log(basket.toString());
        assertNotNull(basket.getValue("id"));
        IProductCatalog catalog = shoppingBusinessService.getProductCatalog();
        for (IDTO product : catalog.getProducts()) {
            logging.log(product.toString());
            String name = (String) product.getValue("name");
            if (name.equals("tires")) {
                CartItemDTO dto = (CartItemDTO) CartItemDTOHome.Instance().newDTOInstance();
                dto.setValue("cart_id", basket.getValue("id"));
                dto.setValue("product_id", product.getValue("id"));
                dto.setValue("quantity", 4);
                List<IDTO> result = shoppingBusinessService.saveDTO(dto);
                dto = (CartItemDTO) result.getFirst();
                assertNotNull(dto.getValue("id"));
            }
        }
        IDTO userProfile = shoppingBusinessService.getUserProfiles((Integer) user.getValue("id")).getFirst();
        ShoppingPaymentService paymentService = shoppingBusinessService.getShoppingPaymentService();
        assertTrue(paymentService.processPayment((Integer) basket.getValue("id"),
                (Integer) userProfile.getValue("id")));
    }
References ShoppingBusinessLayerService.getActiveCart(), ShoppingBusinessLayerService.getProductCatalog(), ShoppingBusinessLayerService.getShoppingPaymentService(), ShoppingBusinessLayerService.getUser(), ShoppingBusinessLayerService.getUserProfiles(), CartItemDTOHome.Instance(), Environment.Instance(), AppLoggingAgent.log(), and ShoppingBusinessLayerService.saveDTO().
testIntegration_GetBasket()
void TestZIntegration.testIntegration_GetBasket () [package]
Definition at line 45 of file TestZIntegration.java.
                                     {
        // get catalog
        ShoppingSystem system = new ShoppingSystem(Environment.Instance());
        system.configure();
        ShoppingBusinessLayerService shoppingBusinessService = system.getShoppingBusinessService();
        UserDTO user = shoppingBusinessService.getUser("joesample");
        logging.log(user.toString());
        assertNotNull(user.getValue("id"));
        IDTO basket = shoppingBusinessService.getActiveCart((Integer) user.getValue("id"));
        logging.log(basket.toString());
        assertNotNull(basket.getValue("id"));
    }
References ShoppingBusinessLayerService.getActiveCart(), ShoppingBusinessLayerService.getUser(), Environment.Instance(), and AppLoggingAgent.log().
testIntegration_GetProductCatalog()
void TestZIntegration.testIntegration_GetProductCatalog () [package]
Definition at line 30 of file TestZIntegration.java.
                                             {
        // get catalog
        ShoppingSystem system = new ShoppingSystem(Environment.Instance());
        system.configure();
        ShoppingBusinessLayerService shoppingBusinessService = system.getShoppingBusinessService();
        IProductCatalog catalog = shoppingBusinessService.getProductCatalog();
        for (IDTO product : catalog.getProducts()) {
            logging.log(product.toString());
        }
        assertNotEquals(0l, (long) catalog.getProducts().size());
    }
References ShoppingBusinessLayerService.getProductCatalog(), Environment.Instance(), and AppLoggingAgent.log().
Member Data Documentation
logging
AppLoggingAgent TestZIntegration.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
Definition at line 16 of file TestZIntegration.java.
The documentation for this class was generated from the following file:
TestZIntegration.java