BaseDTO Class Reference
Public Member Functions
String getDtoName ()
BaseDTO (String dtoName, Map< String, DTOTypes > fields, Map< Integer, String > fieldsOrderMap)
BaseDTO (BaseDTO baseDTO)
Object getValue (String fieldName)
Retrieves the value of a field specified by the given field name.
Boolean setValue (String fieldName, Object value)
Sets the value of a field in the DTO.
Map< String, DTOTypes > getFields ()
Returns a map of fields in the DTO object.
Boolean updateSchema ()
IDbResultProcessor getLoadProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
String getLoadSql (String schema)
Gets the SQL statement for loading data from the database.
IDbResultProcessor getSaveProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
String getSaveSql (String schema)
Gets the SQL statement for saving data to the database.
String toString ()
Public Member Functions inherited from IDTO
IDTOHome getDtoHome ()
This interface represents the home for IDTO objects.
Protected Member Functions
Boolean processLoadResult (ResultSet rs, List< IDTO > loadResults) throws SQLException
Object getValueFromResultSet (ResultSet rs, String fieldName, DTOTypes dtoTypes) throws SQLException
String formatValueForQuery (Object value, DTOTypes dtoTypes)
Boolean processSaveResult (ResultSet rs, List< IDTO > saveResults) throws SQLException
void buildInsertSql (StringBuilder sb, String schema)
void buildUpdateSql (StringBuilder sb, String schema)
Private Member Functions
BaseDTO ()
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
Map< String, DTOTypes > fields = new HashMap<String, DTOTypes>()
Map< Integer, String > fieldsOrderMap = new HashMap<Integer, String>()
Map< String, Object > values = new HashMap<String, Object>()
String dtoName = ""
Detailed Description
Definition at line 11 of file BaseDTO.java.
Constructor & Destructor Documentation
BaseDTO() [1/3]
BaseDTO.BaseDTO () [private]
Definition at line 28 of file BaseDTO.java.
                      {
    }
BaseDTO() [2/3]
BaseDTO.BaseDTO (String dtoName, Map< String, DTOTypes > fields, Map< Integer, String > fieldsOrderMap)
Definition at line 31 of file BaseDTO.java.
                                                                                                      {
        this.dtoName = dtoName;
        this.fields = fields;
        this.fieldsOrderMap = fieldsOrderMap;
    }
References dtoName, fields, and fieldsOrderMap.
BaseDTO() [3/3]
BaseDTO.BaseDTO (BaseDTO baseDTO)
Definition at line 37 of file BaseDTO.java.
                                    {
        this.fields = baseDTO.fields;
        this.fieldsOrderMap = baseDTO.fieldsOrderMap;
        this.values = baseDTO.values;
        this.dtoName = baseDTO.dtoName;
    }
References dtoName, fields, fieldsOrderMap, and values.
Member Function Documentation
buildInsertSql()
void BaseDTO.buildInsertSql (StringBuilder sb, String schema) [protected]
Definition at line 200 of file BaseDTO.java.
                                                                   {
        sb.append("INSERT INTO " + schema + "." + this.getDtoName() + " (");
        for (Map.Entry<String, DTOTypes> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValue(fieldName);
            if (value == null)
                continue;
            sb.append(fieldName + ", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        sb.append(") VALUES (");
        for (Map.Entry<String, DTOTypes> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValue(fieldName);
            if (value == null)
                continue;
            sb.append(formatValueForQuery(value, fieldType) + ", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        sb.append(")");
    }
References fields, formatValueForQuery(), getDtoName(), and getValue().
Referenced by getSaveSql().
buildUpdateSql()
void BaseDTO.buildUpdateSql (StringBuilder sb, String schema) [protected]
Definition at line 224 of file BaseDTO.java.
                                                                   {
        sb.append("UPDATE " + schema + "." + this.getDtoName() + " SET ");
        for (Map.Entry<String, DTOTypes> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValue(fieldName);
            sb.append(fieldName + " = " + formatValueForQuery(value, fieldType) + ", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        sb.append(" WHERE id = " + getValue("id"));
    }
References fields, formatValueForQuery(), getDtoName(), and getValue().
Referenced by getSaveSql().
formatValueForQuery()
String BaseDTO.formatValueForQuery (Object value, DTOTypes dtoTypes) [protected]
Definition at line 87 of file BaseDTO.java.
                                                                          {
        try {
            switch (dtoTypes) {
                case INTEGER:
                    return value + "";
                case DATE:
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss z");
                    sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
                    return formatValueForQuery(sdf.format(value), DTOTypes.STRING);
                default:
                    return "'" + value + "'";
            }
        } catch (Exception e) {
            logging.log(value.toString(), e);
            throw e;
        }
    }
References formatValueForQuery(), AppLoggingAgent.log(), logging, and DTOTypes.STRING.
Referenced by buildInsertSql(), buildUpdateSql(), formatValueForQuery(), and getLoadSql().
getDtoName()
String BaseDTO.getDtoName ()
Returns
the dtoName
Implements IDTO.
Definition at line 24 of file BaseDTO.java.
                               {
        return dtoName;
    }
References dtoName.
Referenced by buildInsertSql(), buildUpdateSql(), getLoadSql(), and toString().
getFields()
Map< String, DTOTypes > BaseDTO.getFields ()
Returns a map of fields in the DTO object.
Returns
a map containing the fields of the DTO object
Implements IDTO.
Definition at line 55 of file BaseDTO.java.
                                             {
        return fields;
    }
References fields.
getLoadProcessor()
IDbResultProcessor BaseDTO.getLoadProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
Returns
the IDbResultProcessor associated with this IDTO
Implements IDTO.
Definition at line 106 of file BaseDTO.java.
                                                 {
        class LoadResultProcessor implements IDbResultProcessor {
            private IDTO dto;
            LoadResultProcessor(IDTO dto) {
                this.dto = dto;
            }
            @Override
            public Boolean process(ResultSet rs) throws SQLException {
                return processLoadResult(rs, loadResults);
            }
            private List<IDTO> loadResults = new ArrayList<>();
            public List<IDTO> getResults() {
                return loadResults;
            }
        }
        return new LoadResultProcessor(this);
    }
getLoadSql()
String BaseDTO.getLoadSql (String schema)
Gets the SQL statement for loading data from the database.
Returns
The SQL statement for loading data.
Implements IDTO.
Definition at line 130 of file BaseDTO.java.
                                            {
        StringBuilder sb = new StringBuilder();
        Boolean isFirst = true;
        sb.append("SELECT * FROM " + schema + "." + this.getDtoName() + " WHERE ");
        for (Map.Entry<String, DTOTypes> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValue(fieldName);
            if (value == null)
                continue;
            if (!isFirst)
                sb.append(" AND ");
            else
                isFirst = false;
            sb.append(fieldName + " = " + formatValueForQuery(value, fieldType));
        }
        return sb.toString();
    }
References fields, formatValueForQuery(), getDtoName(), and getValue().
getSaveProcessor()
IDbResultProcessor BaseDTO.getSaveProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
Returns
the IDbResultProcessor associated with this IDTO
Implements IDTO.
Definition at line 164 of file BaseDTO.java.
                                                 {
        class SaveResultProcessor implements IDbResultProcessor {
            private IDTO dto;
            SaveResultProcessor(IDTO dto) {
                this.dto = dto;
            }
            @Override
            public Boolean process(ResultSet rs) throws SQLException {
                return processSaveResult(rs, saveResults);
            }
            private List<IDTO> saveResults = Arrays.asList(this.dto);
            public List<IDTO> getResults() {
                return saveResults;
            }
        }
        return new SaveResultProcessor(this);
    }
getSaveSql()
String BaseDTO.getSaveSql (String schema)
Gets the SQL statement for saving data to the database.
Returns
The SQL statement for saving data.
Implements IDTO.
Definition at line 187 of file BaseDTO.java.
                                            {
        StringBuilder sb = new StringBuilder();
        Object value = getValue("id");
        Boolean isInsert = value == null;
        if (isInsert)
            buildInsertSql(sb, schema);
        else
            buildUpdateSql(sb, schema);
        return sb.toString();
    }
References buildInsertSql(), buildUpdateSql(), and getValue().
getValue()
Object BaseDTO.getValue (String fieldName)
Retrieves the value of a field specified by the given field name.
Parameters
fieldName the name of the field
Returns
the value of the field
Implements IDTO.
Definition at line 44 of file BaseDTO.java.
                                             {
        if (values.containsKey(fieldName))
            return values.get(fieldName);
        return null;
    }
References values.
Referenced by buildInsertSql(), buildUpdateSql(), getLoadSql(), getSaveSql(), and toString().
getValueFromResultSet()
Object BaseDTO.getValueFromResultSet (ResultSet rs, String fieldName, DTOTypes dtoTypes) throws SQLException [protected]
Definition at line 76 of file BaseDTO.java.
                                                                                                                  {
        switch (dtoTypes) {
            case INTEGER:
                return rs.getInt(fieldName);
            case DATE:
                return rs.getDate(fieldName);
            default:
                return rs.getString(fieldName);
        }
    }
Referenced by processLoadResult(), and processSaveResult().
processLoadResult()
Boolean BaseDTO.processLoadResult (ResultSet rs, List< IDTO > loadResults) throws SQLException [protected]
Definition at line 63 of file BaseDTO.java.
                                                                                                  {
        if (rs == null)
            return false;
        for (Map.Entry<String, DTOTypes> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValueFromResultSet(rs, fieldName, fieldType);
            setValue(fieldName, value);
        }
        loadResults.add(this);
        return true;
    }
References fields, getValueFromResultSet(), and setValue().
processSaveResult()
Boolean BaseDTO.processSaveResult (ResultSet rs, List< IDTO > saveResults) throws SQLException [protected]
Definition at line 150 of file BaseDTO.java.
                                                                                                  {
        if (rs == null)
            return false;
        for (Map.Entry<String, DTOTypes> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValueFromResultSet(rs, fieldName, fieldType);
            setValue(fieldName, value);
        }
        saveResults.add(this);
        return true;
    }
References fields, getValueFromResultSet(), and setValue().
setValue()
Boolean BaseDTO.setValue (String fieldName, Object value)
Sets the value of a field in the DTO.
Parameters
fieldName the name of the field
value the value to be set
Returns
true if the value was successfully set, false otherwise
Implements IDTO.
Definition at line 50 of file BaseDTO.java.
                                                            {
        values.put(fieldName, value);
        return true;
    }
References values.
Referenced by processLoadResult(), and processSaveResult().
toString()
String BaseDTO.toString ()
Definition at line 237 of file BaseDTO.java.
                             {
        StringBuilder sb = new StringBuilder();
        sb.append(this.getDtoName() + ": ");
        for (Map.Entry<String, DTOTypes> entry : fields.entrySet()) {
            String fieldName = entry.getKey();
            DTOTypes fieldType = entry.getValue();
            Object value = getValue(fieldName);
            sb.append(fieldName + " = " + value + ", ");
        }
        sb.delete(sb.length() - 2, sb.length());
        return sb.toString();
    }
References fields, getDtoName(), and getValue().
updateSchema()
Boolean BaseDTO.updateSchema ()
Definition at line 59 of file BaseDTO.java.
                                  {
        return false;
    }
Member Data Documentation
dtoName
String BaseDTO.dtoName = "" [private]
Definition at line 18 of file BaseDTO.java.
Referenced by BaseDTO(), BaseDTO(), and getDtoName().
fields
Map<String, DTOTypes> BaseDTO.fields = new HashMap<String, DTOTypes>() [private]
Definition at line 15 of file BaseDTO.java.
Referenced by BaseDTO(), BaseDTO(), buildInsertSql(), buildUpdateSql(), getFields(), getLoadSql(), processLoadResult(), processSaveResult(), and toString().
fieldsOrderMap
Map<Integer, String> BaseDTO.fieldsOrderMap = new HashMap<Integer, String>() [private]
Definition at line 16 of file BaseDTO.java.
Referenced by BaseDTO(), and BaseDTO().
logging
AppLoggingAgent BaseDTO.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
Definition at line 13 of file BaseDTO.java.
Referenced by formatValueForQuery().
values
Map<String, Object> BaseDTO.values = new HashMap<String, Object>() [private]
Definition at line 17 of file BaseDTO.java.
Referenced by BaseDTO(), getValue(), and setValue().
The documentation for this class was generated from the following file:
BaseDTO.java