ShoppingDataLayerService Class Reference
The ShoppingDataLayerService class is responsible for handling data layer operations related to shopping functionality.
Public Member Functions
ShoppingDataLayerService (IEnvironment environment)
void configure ()
Configures the shopping data layer service.
List< IDTO > executeCommand (String sql, IDbResultProcessor resultProcessor)
Executes a database command and returns a Boolean indicating the success or failure of the operation.
List< IDTO > executeQuery (String sql, IDbResultProcessor resultProcessor)
Executes a SQL query and processes the result using the specified IDbResultProcessor.
List< IDTO > loadDTOs (IDTO dto, IDTOHome dtoHome)
Loads the specified DTO using the provided SQL query and processor.
List< IDTO > saveDTO (IDTO dto)
Saves the given DTO object.
List< IDTO > saveDTOs (List< IDTO > dtos)
Saves a list of IDTO objects.
Static Package Functions
[static initializer]
Private Member Functions
void loadConfiguration (IEnvironment environment)
Loads the configuration values from the given environment object.
void getDatabaseConnectionInformation (IDbConnectionWrapper dbConnectionWrapper)
Prompts the user to enter database connection information and sets the connection properties for the given IDbConnectionWrapper object.
Private Attributes
AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The logging agent used for logging in the shopping data layer service.
IEnvironment environment
Represents an interface for accessing the environment settings.
String driver
The driver used for the shopping data layer service.
String userName
The username associated with the shopping data layer service.
String password
The password used for authentication.
String host
The host of the shopping data layer service.
String database
The name of the database used by the shopping data layer service.
int port
The port number used by the ShoppingDataLayerService.
String schema
The schema used for the shopping data layer service.
Detailed Description
The ShoppingDataLayerService class is responsible for handling data layer operations related to shopping functionality.
Definition at line 10 of file ShoppingDataLayerService.java.
Constructor & Destructor Documentation
ShoppingDataLayerService()
ShoppingDataLayerService.ShoppingDataLayerService (IEnvironment environment)
Definition at line 56 of file ShoppingDataLayerService.java.
                                                              {
        this.environment = environment;
    }
References environment.
Member Function Documentation
[static initializer]()
ShoppingDataLayerService.[static initializer] [static], [package]
configure()
void ShoppingDataLayerService.configure ()
Configures the shopping data layer service.
Loads the configuration based on the current environment.
Definition at line 64 of file ShoppingDataLayerService.java.
                            {
        loadConfiguration(this.environment);
    }
References loadConfiguration().
Referenced by ShoppingSystem.configure().
executeCommand()
List< IDTO > ShoppingDataLayerService.executeCommand (String sql, IDbResultProcessor resultProcessor)
Executes a database command and returns a Boolean indicating the success or failure of the operation.
Parameters
sql The SQL command to be executed.
resultProcessor The result processor for handling the query result.
Returns
true if the command is executed successfully, false otherwise.
Definition at line 94 of file ShoppingDataLayerService.java.
                                                                                     {
        try (IDbConnectionWrapper dbConnectionWrapper = DbFactory.create(this.driver)) {
            getDatabaseConnectionInformation(dbConnectionWrapper);
            Boolean result = (new ExecuteQueryOperation()).execute(dbConnectionWrapper, sql, resultProcessor);
            if (result) {
                return resultProcessor.getResults();
            }
        } catch (Exception e) {
            logging.log("Error executing command", e);
        }
        return new ArrayList<IDTO>();
    }
References IFactory< T >.create(), getDatabaseConnectionInformation(), AppLoggingAgent.log(), and logging.
Referenced by saveDTO().
executeQuery()
List< IDTO > ShoppingDataLayerService.executeQuery (String sql, IDbResultProcessor resultProcessor)
Executes a SQL query and processes the result using the specified IDbResultProcessor.
Parameters
sql The SQL query to execute.
resultProcessor The IDbResultProcessor to process the query result.
Returns
true if the query was executed successfully, false otherwise.
Definition at line 115 of file ShoppingDataLayerService.java.
                                                                                   {
        try (IDbConnectionWrapper dbConnectionWrapper = DbFactory.create(this.driver)) {
            getDatabaseConnectionInformation(dbConnectionWrapper);
            Boolean result = (new SimpleQueryOperation()).execute(dbConnectionWrapper, sql, resultProcessor);
            if (result)
                return resultProcessor.getResults();
        } catch (Exception e) {
            logging.log("Error executing command", e);
        }
        return new ArrayList<IDTO>();
    }
References IFactory< T >.create(), getDatabaseConnectionInformation(), AppLoggingAgent.log(), and logging.
Referenced by loadDTOs().
getDatabaseConnectionInformation()
void ShoppingDataLayerService.getDatabaseConnectionInformation (IDbConnectionWrapper dbConnectionWrapper) [private]
Prompts the user to enter database connection information and sets the connection properties for the given IDbConnectionWrapper object.
Parameters
dbConnectionWrapper the IDbConnectionWrapper object to set the connection properties for
Definition at line 136 of file ShoppingDataLayerService.java.
                                                                                            {
        dbConnectionWrapper.connectionProperties(this.userName, this.password, this.port, this.host, this.database,
                this.schema);
    }
Referenced by executeCommand(), and executeQuery().
loadConfiguration()
void ShoppingDataLayerService.loadConfiguration (IEnvironment environment) [private]
Loads the configuration values from the given environment object.
Sets the driver, username, password, host, database, and port for the database connection.
Parameters
environment the environment object containing the configuration values
Definition at line 75 of file ShoppingDataLayerService.java.
                                                             {
        this.driver = environment.getValue("db.driver");
        this.userName = environment.getValue("db.user");
        this.password = environment.getValue("db.password");
        this.host = environment.getValue("db.host");
        this.database = environment.getValue("db.database");
        this.port = Integer.parseInt(environment.getValue("db.port"));
        this.schema = environment.getValue("db.schema");
    }
References environment, and IEnvironment.getValue().
Referenced by configure().
loadDTOs()
List< IDTO > ShoppingDataLayerService.loadDTOs (IDTO dto, IDTOHome dtoHome)
Loads the specified DTO using the provided SQL query and processor.
Parameters
dto The DTO to be loaded.
Returns
True if the DTO was successfully loaded, false otherwise.
Definition at line 147 of file ShoppingDataLayerService.java.
                                                           {
        return executeQuery(dto.getLoadSql(this.schema), dtoHome.getLoadProcessor());
    }
References executeQuery().
Referenced by ShoppingBusinessLayerService.getCart(), ShoppingBusinessLayerService.getCartByStatus(), ShoppingBusinessLayerService.getCartItems(), ShoppingBusinessLayerService.getOrder(), ShoppingBusinessLayerService.getPaymentProfile(), ShoppingBusinessLayerService.getPaymentProfiles(), ShoppingBusinessLayerService.getProductById(), ShoppingBusinessLayerService.getProductCatalog(), ShoppingBusinessLayerService.getRoles(), ShoppingBusinessLayerService.getUser(), ShoppingBusinessLayerService.getUser(), ShoppingBusinessLayerService.getUserDTO(), ShoppingBusinessLayerService.getUserProfiles(), ShoppingBusinessLayerService.getUserRoles(), ShoppingBusinessLayerService.loadDTOs(), and saveDTO().
saveDTO()
List< IDTO > ShoppingDataLayerService.saveDTO (IDTO dto)
Saves the given DTO object.
Parameters
dto The DTO object to be saved.
Returns
True if the DTO object is successfully saved, false otherwise.
Definition at line 157 of file ShoppingDataLayerService.java.
                                        {
        List<IDTO> result = executeCommand(dto.getSaveSql(this.schema), dto.getSaveProcessor());
        for (IDTO dtoResult : result) {
            return loadDTOs(dto, dto.getDtoHome());
        }
        return new ArrayList<IDTO>();
    }
References executeCommand(), and loadDTOs().
Referenced by ShoppingBusinessLayerService.addAuditTrail(), ShoppingBusinessLayerService.saveDTO(), and saveDTOs().
saveDTOs()
List< IDTO > ShoppingDataLayerService.saveDTOs (List< IDTO > dtos)
Saves a list of IDTO objects.
Parameters
dtos The list of IDTO objects to be saved.
Returns
The same list of IDTO objects.
Definition at line 171 of file ShoppingDataLayerService.java.
                                                {
        for (IDTO dto : dtos) {
            if (saveDTO(dto).size() == 0)
                logging.log("Error saving DTO: " + dto.getDtoName() + " " + dto.toString());
        }
        return dtos;
    }
References AppLoggingAgent.log(), logging, and saveDTO().
Member Data Documentation
database
String ShoppingDataLayerService.database [private]
The name of the database used by the shopping data layer service.
Definition at line 45 of file ShoppingDataLayerService.java.
driver
String ShoppingDataLayerService.driver [private]
The driver used for the shopping data layer service.
Definition at line 29 of file ShoppingDataLayerService.java.
environment
IEnvironment ShoppingDataLayerService.environment [private]
Represents an interface for accessing the environment settings.
Definition at line 25 of file ShoppingDataLayerService.java.
Referenced by loadConfiguration(), and ShoppingDataLayerService().
host
String ShoppingDataLayerService.host [private]
The host of the shopping data layer service.
Definition at line 41 of file ShoppingDataLayerService.java.
logging
AppLoggingAgent ShoppingDataLayerService.logging = new AppLoggingAgent(new AppLoggingStream()) [private]
The logging agent used for logging in the shopping data layer service.
Definition at line 15 of file ShoppingDataLayerService.java.
Referenced by executeCommand(), executeQuery(), and saveDTOs().
password
String ShoppingDataLayerService.password [private]
The password used for authentication.
Definition at line 37 of file ShoppingDataLayerService.java.
port
int ShoppingDataLayerService.port [private]
The port number used by the ShoppingDataLayerService.
Definition at line 49 of file ShoppingDataLayerService.java.
schema
String ShoppingDataLayerService.schema [private]
The schema used for the shopping data layer service.
Definition at line 54 of file ShoppingDataLayerService.java.
userName
String ShoppingDataLayerService.userName [private]
The username associated with the shopping data layer service.
Definition at line 33 of file ShoppingDataLayerService.java.
The documentation for this class was generated from the following file:
ShoppingDataLayerService.java