CoreUtils Class Reference
The CoreUtils class provides utility methods for encoding strings using SHA-256 algorithm.
Static Public Member Functions
static String encodeSha256String (final String unencodedString)
Encodes a string using SHA-256 algorithm and returns the encoded string.
static byte[] encodeSha256Bytes (final String unencodedString)
Encodes a string using SHA-256 algorithm and returns the encoded bytes.
static String bytesToHex (byte[] hash)
Converts a byte array to a hexadecimal string representation.
Private Member Functions
CoreUtils ()
Static Private Attributes
static AppLoggingAgent logging = new AppLoggingAgent(new AppLoggingStream())
The logging agent used for logging application events.
static Object digestLock = new Object()
A lock object used for synchronization when accessing the digest.
Detailed Description
The CoreUtils class provides utility methods for encoding strings using SHA-256 algorithm.
Definition at line 7 of file CoreUtils.java.
Constructor & Destructor Documentation
CoreUtils()
CoreUtils.CoreUtils () [private]
Definition at line 14 of file CoreUtils.java.
                        {
    }
Member Function Documentation
bytesToHex()
static String CoreUtils.bytesToHex (byte[] hash) [static]
Converts a byte array to a hexadecimal string representation.
Parameters
hash the byte array to be converted
Returns
the hexadecimal string representation of the byte array
Definition at line 63 of file CoreUtils.java.
                                                 {
        StringBuilder hexString = new StringBuilder(2 * hash.length);
        for (int i = 0; i < hash.length; i++) {
            String hex = Integer.toHexString(0xff & hash[i]);
            if (hex.length() == 1) {
                hexString.append('0');
            }
            hexString.append(hex);
        }
        return hexString.toString();
    }
Referenced by encodeSha256String().
encodeSha256Bytes()
static byte[] CoreUtils.encodeSha256Bytes (final String unencodedString) [static]
Encodes a string using SHA-256 algorithm and returns the encoded bytes.
Parameters
unencodedString the string to be encoded
Returns
the encoded bytes
Exceptions
RuntimeException if an error occurs during encoding
Definition at line 45 of file CoreUtils.java.
                                                                         {
        try {
            synchronized (digestLock) {
                MessageDigest digest = MessageDigest.getInstance("SHA-256");
                return digest.digest(unencodedString.getBytes(StandardCharsets.UTF_8));
            }
        } catch (Exception ex) {
            logging.log("Error encoding string", ex);
            throw new RuntimeException(ex);
        }
    }
References digestLock, AppLoggingAgent.log(), and logging.
Referenced by encodeSha256String().
encodeSha256String()
static String CoreUtils.encodeSha256String (final String unencodedString) [static]
Encodes a string using SHA-256 algorithm and returns the encoded string.
Parameters
unencodedString the string to be encoded
Returns
the encoded string
Exceptions
RuntimeException if an error occurs during encoding
Definition at line 29 of file CoreUtils.java.
                                                                          {
        try {
            return bytesToHex(encodeSha256Bytes(unencodedString));
        } catch (Exception ex) {
            logging.log("Error encoding string", ex);
            throw new RuntimeException(ex);
        }
    }
References bytesToHex(), encodeSha256Bytes(), AppLoggingAgent.log(), and logging.
Referenced by TestDTO.testUserDTO_1(), TestDTO.testUserDTO_2(), TestDTO.testUserDTO_3(), and ShoppingBusinessLayerService.validateLogin().
Member Data Documentation
digestLock
Object CoreUtils.digestLock = new Object() [static], [private]
A lock object used for synchronization when accessing the digest.
Definition at line 20 of file CoreUtils.java.
Referenced by encodeSha256Bytes().
logging
AppLoggingAgent CoreUtils.logging = new AppLoggingAgent(new AppLoggingStream()) [static], [private]
The logging agent used for logging application events.
Definition at line 12 of file CoreUtils.java.
Referenced by encodeSha256Bytes(), and encodeSha256String().
The documentation for this class was generated from the following file:
CoreUtils.java