EchoHandler Class Reference
Public Member Functions
void handle (HttpExchange httpExchange) throws IOException
Handles the incoming HTTP request and generates an appropriate response.
Public Member Functions inherited from BaseRouteHandler
String buildResponse (String responseString, HttpResponseTextType responseType)
Builds a response string based on the given response string and response type.
Private Member Functions
String handleGetRequest (HttpExchange httpExchange)
Handles the GET request and returns a formatted string containing information about the request.
String handlePostRequest (HttpExchange httpExchange)
Handles a POST request by delegating to the handleGetRequest method.
Additional Inherited Members
Protected Member Functions inherited from BaseRouteHandler
String buildResponse (String responseString)
Builds a response string.
void handleResponse (HttpExchange httpExchange, String responseString, Integer responseCode) throws IOException
Handles the HTTP response by sending the specified response string and response code.
void handleResponse (HttpExchange httpExchange, HttpResponseTextType responseType, String responseString, Integer responseCode) throws IOException
Handles the HTTP response by setting the response content type, sending the response headers, and writing the response string to the output stream.
void setResponseContentType (HttpExchange httpExchange)
Sets the response content type for the given HttpExchange object.
void setResponseContentType (HttpExchange httpExchange, HttpResponseTextType responseType)
Sets the response content type based on the specified HttpResponseTextType.
IHttpRequestContextInfo processUri (HttpExchange httpExchange)
Processes the URI of the HTTP request and returns an instance of IHttpRequestContextInfo.
void addCookie (HttpExchange httpExchange, IHttpCookie cookie)
Adds a cookie to the response headers of the given HttpExchange.
Static Protected Member Functions inherited from BaseRouteHandler
static Map< String, String > parseFormData (String formData) throws UnsupportedEncodingException
Parses the given form data and returns a map of key-value pairs.
Protected Attributes inherited from BaseRouteHandler
AppLoggingAgent logger = new AppLoggingAgent(new AppLoggingStream())
Detailed Description
Definition at line 6 of file EchoHandler.java.
Member Function Documentation
handle()
void EchoHandler.handle (HttpExchange httpExchange) throws IOException
Handles the incoming HTTP request and generates an appropriate response.
Parameters
httpExchange The HTTP exchange object representing the request and response.
Exceptions
IOException If an I/O error occurs while handling the request.
Definition at line 14 of file EchoHandler.java.
                                                                     {
        String buildResponse = "";
        int responseCode = 500;
        try {
            String requestParamValue = null;
            logger.log("httpExchange: " + httpExchange.getRequestMethod() + " " + httpExchange.getRequestURI());
            if ("GET".equals(httpExchange.getRequestMethod())) {
                requestParamValue = handleGetRequest(httpExchange);
            } else if ("POST".equals(httpExchange.getRequestMethod())) {
                requestParamValue = handlePostRequest(httpExchange);
            }
            buildResponse = buildResponse(requestParamValue);
            logger.log("Response: " + buildResponse);
        } catch (Exception e) {
            logger.log("Error handling request", e);
            buildResponse = buildResponse(e.getMessage());
            responseCode = 500;
        }
        this.handleResponse(httpExchange, buildResponse, responseCode);
    }
References BaseRouteHandler.buildResponse(), handleGetRequest(), handlePostRequest(), BaseRouteHandler.handleResponse(), AppLoggingAgent.log(), and BaseRouteHandler.logger.
handleGetRequest()
String EchoHandler.handleGetRequest (HttpExchange httpExchange) [private]
Handles the GET request and returns a formatted string containing information about the request.
Parameters
httpExchange The HttpExchange object representing the HTTP request and response.
Returns
A formatted string containing information about the request.
Definition at line 43 of file EchoHandler.java.
                                                               {
        IHttpRequestContextInfo contextInfo = new HttpRequestContextInfo(httpExchange);
        Map<String, String> queryMap = contextInfo.getQueryMap();
        String uri = contextInfo.getUri();
        String path = contextInfo.getUriPath();
        String queryMapString = queryMap.toString();
        String body = httpExchange.getRequestBody().toString();
        return "<br> 'URI' : '" + HttpHelpers.escapeResponseString(uri)
                + "' <br> 'path' : '" + HttpHelpers.escapeResponseString(path)
                + "' <br> 'body' : '" + HttpHelpers.escapeResponseString(body)
                + "' <br> 'queryParams' : '" + HttpHelpers.escapeResponseString(queryMapString)
                + "' <br>";
    }
References HttpHelpers.escapeResponseString(), IHttpRequestContextInfo.getQueryMap(), IHttpRequestContextInfo.getUri(), and IHttpRequestContextInfo.getUriPath().
Referenced by handle(), and handlePostRequest().
handlePostRequest()
String EchoHandler.handlePostRequest (HttpExchange httpExchange) [private]
Handles a POST request by delegating to the handleGetRequest method.
Parameters
httpExchange The HttpExchange object representing the HTTP request and response.
Returns
The response string generated by the handleGetRequest method.
Definition at line 63 of file EchoHandler.java.
                                                                {
        return handleGetRequest(httpExchange);
    }
References handleGetRequest().
Referenced by handle().
The documentation for this class was generated from the following file:
EchoHandler.java