AppLoggingAgent Class Reference
The AppLoggingAgent class implements the IAppLoggingStream interface and provides methods for logging messages, objects, arrays of messages, and throwable objects to the application stream.
Public Member Functions
AppLoggingAgent (IAppLoggingStream appStream)
void log (String message)
The log function logs a message to the application stream.
void log (Object object)
The log function logs an object to the application stream.
void log (String[] messages)
The log function takes an array of messages and logs them using the _appStream object.
void log (Throwable throwable)
The log function logs a throwable object to the app stream.
void log (String message, Throwable throwable)
The log function logs a message and a throwable object.
void flush ()
The flush() function flushes the output stream.
Public Attributes
IAppLoggingStream appStream
The appStream property is an instance of the IAppLoggingStream interface.
Static Private Member Functions
static String getCallingMethodInfo ()
Returns the calling method information as a string.
static String getLogHeaderString ()
Returns a string representation of the log header.
Detailed Description
The AppLoggingAgent class implements the IAppLoggingStream interface and provides methods for logging messages, objects, arrays of messages, and throwable objects to the application stream.
It also provides a method for flushing the output stream.
Definition at line 11 of file AppLoggingAgent.java.
Constructor & Destructor Documentation
AppLoggingAgent()
AppLoggingAgent.AppLoggingAgent (IAppLoggingStream appStream)
Parameters
appStream
Definition at line 21 of file AppLoggingAgent.java.
                                                        {
        this.appStream = appStream;
    }
References appStream.
Member Function Documentation
flush()
void AppLoggingAgent.flush ()
The flush() function flushes the output stream.
Implements IAppLoggingStream.
Definition at line 136 of file AppLoggingAgent.java.
                        {
        this.appStream.flush();
    }
References IAppLoggingStream.flush().
getCallingMethodInfo()
static String AppLoggingAgent.getCallingMethodInfo () [static], [private]
Returns the calling method information as a string.
Returns
the calling method information
Definition at line 30 of file AppLoggingAgent.java.
                                                 {
        Thread currentThread = Thread.currentThread();
        StackTraceElement stack = currentThread.getStackTrace()[4];
        StringBuffer sb = new StringBuffer();
        sb
                .append(stack.getClassName())
                .append(".")
                .append(stack.getMethodName())
                .append(":")
                .append(stack.getLineNumber())
                .append(" | ")
                .append(currentThread.threadId());
        return sb.toString();
    }
Referenced by getLogHeaderString().
getLogHeaderString()
static String AppLoggingAgent.getLogHeaderString () [static], [private]
Returns a string representation of the log header.
Returns
the log header string
Definition at line 52 of file AppLoggingAgent.java.
                                               {
        StringBuffer sb = new StringBuffer();
        sb
                .append(Instant.now().toString())
                .append(" | ")
                .append(getCallingMethodInfo())
                .append(" | ");
        return sb.toString();
    }
References getCallingMethodInfo().
Referenced by log(), log(), log(), log(), and log().
log() [1/5]
void AppLoggingAgent.log (Object object)
The log function logs an object to the application stream.
Parameters
object The "object" parameter is an instance of the Object class, which is the base class for all classes in Java. It represents an object that can be used to store any type of data.
Implements IAppLoggingStream.
Definition at line 83 of file AppLoggingAgent.java.
                                   {
        this.appStream.log(getLogHeaderString() + object.toString());
    }
References getLogHeaderString(), and IAppLoggingStream.log().
log() [2/5]
void AppLoggingAgent.log (String message)
The log function logs a message to the application stream.
Parameters
message The message parameter is a string that represents the log message that you want to log.
Implements IAppLoggingStream.
Definition at line 70 of file AppLoggingAgent.java.
                                    {
        this.appStream.log(getLogHeaderString() + message);
    }
References getLogHeaderString(), and IAppLoggingStream.log().
Referenced by BaseRouteHandler.buildResponse(), DbBaseFactoryWrapper.close(), DbBaseFactoryWrapper.connectionProperties(), IFactory< T >.create(), DbBaseFactoryWrapper_postgres.DbBaseFactoryWrapper_postgres(), CoreUtils.encodeSha256Bytes(), CoreUtils.encodeSha256String(), Environment.Environment(), DbBaseFactoryWrapper.execute(), ShoppingDataLayerService.executeCommand(), ShoppingDataLayerService.executeQuery(), BaseDTO.formatValueForQuery(), BaseShoppingSystemHandler.handle(), EchoHandler.handle(), BaseRouteHandler.handleResponse(), IFactory< T >.processPath(), DbBaseFactoryWrapper.query(), DbUtils.resultSetToString(), ShoppingDataLayerService.saveDTOs(), TestDTO.testCartDTO_1(), TestDTO.testCartDTO_2(), TestDTO.testCartItemDTO_1(), TestDTO.testCartItemDTO_2(), TestDTO.testOrderDTO_1(), TestDTO.testOrderDTO_2(), TestDTO.testOrderItemDTO_1(), TestDTO.testPaymentProfileDTO_1(), TestDTO.testPaymentProfileDTO_2(), TestDTO.testProductDTO_1(), TestDTO.testProductDTO_2(), TestDTO.testProductDTO_3(), TestDTO.testProductDTO_4(), TestDTO.testPurchaseDTO_1(), TestDTO.testPurchaseDTO_2(), TestDTO.testRoleDTO_1(), TestDTO.testRoleDTO_2(), TestDTO.testUserDTO_1(), TestDTO.testUserDTO_2(), TestDTO.testUserDTO_3(), TestDTO.testUserProfileDTO_1(), TestDTO.testUserProfileDTO_2(), TestDTO.testUserRoleDTO_1(), and TestDTO.testUserRoleDTO_2().
log() [3/5]
void AppLoggingAgent.log (String message, Throwable throwable)
The log function logs a message and a throwable object.
Parameters
message The message parameter is a string that represents the log message to be logged. It can contain any information that you want to include in the log, such as error messages, debug information, or general information about the state of the application.
throwable The "throwable" parameter is used to pass an exception or error object. It allows you to log an exception along with a message.
Implements IAppLoggingStream.
Definition at line 129 of file AppLoggingAgent.java.
                                                         {
        this.appStream.log(getLogHeaderString() + message, throwable);
    }
References getLogHeaderString(), and IAppLoggingStream.log().
log() [4/5]
void AppLoggingAgent.log (String[] messages)
The log function takes an array of messages and logs them using the _appStream object.
Parameters
messages The "messages" parameter is an array of strings. It is used to pass multiple log messages to the "log" method.
Implements IAppLoggingStream.
Definition at line 95 of file AppLoggingAgent.java.
                                       {
        ArrayList<String> logMessages = new ArrayList<String>();
        for (String message : messages) {
            logMessages.add(getLogHeaderString() + message);
        }
        this.appStream.log(logMessages);
    }
References getLogHeaderString(), and IAppLoggingStream.log().
log() [5/5]
void AppLoggingAgent.log (Throwable throwable)
The log function logs a throwable object to the app stream.
Parameters
throwable The "throwable" parameter is an instance of the Throwable class, which represents an object that can be thrown and caught. It is typically used to handle exceptions and errors in Java.
Implements IAppLoggingStream.
Definition at line 112 of file AppLoggingAgent.java.
                                         {
        this.appStream.log(getLogHeaderString(), throwable);
    }
References getLogHeaderString(), and IAppLoggingStream.log().
Member Data Documentation
appStream
IAppLoggingStream AppLoggingAgent.appStream
The appStream property is an instance of the IAppLoggingStream interface.
Definition at line 16 of file AppLoggingAgent.java.
Referenced by AppLoggingAgent().
The documentation for this class was generated from the following file:
AppLoggingAgent.java