AppLoggingStream Class Reference
The AppLoggingStream class implements the IAppLoggingStream interface and provides methods for logging messages to an output stream.
Public Member Functions
void log (String[] messages)
The log function takes an array of strings as input and prints each string to the output stream, followed by flushing the stream.
void log (Object object)
The log function takes an object as input and prints the object's string representation to the output stream, followed by flushing the stream.
void log (String message)
The log function prints a message to the output stream and flushes it.
void log (Throwable throwable)
The log function prints the error message and stack trace of a Throwable object to an output stream.
void log (String message, Throwable throwable)
The log function prints a message, the throwable's message, and the stack trace to the output stream.
void flush ()
The flush() function flushes the output stream.
Private Attributes
PrintStream oStream = System.out
The oStream property is an instance of the PrintStream class.
Detailed Description
The AppLoggingStream class implements the IAppLoggingStream interface and provides methods for logging messages to an output stream.
It includes methods for logging strings, objects, and throwables, as well as a method for flushing the output stream.
Definition at line 11 of file AppLoggingStream.java.
Member Function Documentation
flush()
void AppLoggingStream.flush ()
The flush() function flushes the output stream.
Implements IAppLoggingStream.
Definition at line 100 of file AppLoggingStream.java.
                        {
        this.oStream.flush();
    }
log() [1/5]
void AppLoggingStream.log (Object object)
The log function takes an object as input and prints the object's string representation to the output stream, followed by flushing the stream.
Parameters
object The "object" parameter is an instance of the Object class, which is the base class for all classes in Java. It represents an object that can be used to store any type of data.
Implements IAppLoggingStream.
Definition at line 43 of file AppLoggingStream.java.
                                   {
        this.log(object.toString());
    }
References log().
log() [2/5]
void AppLoggingStream.log (String message)
The log function prints a message to the output stream and flushes it.
Parameters
message The message parameter is a string that represents the log message that you want to print.
Implements IAppLoggingStream.
Definition at line 54 of file AppLoggingStream.java.
                                    {
        this.oStream.println(message);
        this.oStream.flush();
    }
log() [3/5]
void AppLoggingStream.log (String message, Throwable throwable)
The log function prints a message, the throwable's message, and the stack trace to the output stream.
Parameters
message A string message that you want to log. This can be any information or description that you want to include in the log.
throwable The "throwable" parameter is an object of type Throwable, which represents an exception or error that has occurred in the code. It can be used to retrieve information about the exception, such as its message and stack trace.
Implements IAppLoggingStream.
Definition at line 90 of file AppLoggingStream.java.
                                                         {
        this.oStream.println(message);
        this.oStream.println(throwable.getMessage());
        throwable.printStackTrace(this.oStream);
        this.oStream.flush();
    }
log() [4/5]
void AppLoggingStream.log (String[] messages)
The log function takes an array of strings as input and prints each string to the output stream, followed by flushing the stream.
Parameters
messages An array of strings containing the messages to be logged.
Implements IAppLoggingStream.
Definition at line 25 of file AppLoggingStream.java.
                                       {
        for (String message : messages) {
            this.oStream.println(message);
        }
        this.oStream.flush();
    }
Referenced by log(), and log().
log() [5/5]
void AppLoggingStream.log (Throwable throwable)
The log function prints the error message and stack trace of a Throwable object to an output stream.
Parameters
throwable The "throwable" parameter is an instance of the Throwable class, which represents an object that can be thrown and caught. It can be any subclass of Throwable, such as Exception or Error. In this method, the throwable object is used to log an error message and stack trace.
Implements IAppLoggingStream.
Definition at line 72 of file AppLoggingStream.java.
                                         {
        this.log("", throwable);
    }
References log().
Member Data Documentation
oStream
PrintStream AppLoggingStream.oStream = System.out [private]
The oStream property is an instance of the PrintStream class.
Definition at line 16 of file AppLoggingStream.java.
The documentation for this class was generated from the following file:
AppLoggingStream.java