IHttpRequestContextInfo Interface Reference
This interface represents the information about an HTTP request context.
Public Member Functions
HttpExchange getHttpExchange ()
Returns the HttpExchange object associated with the request.
String getUri ()
Returns the URI of the request.
String getUriPath ()
Returns the path component of the URI.
String getQueryString ()
Returns the query string of the URI.
Map< String, String > getQueryMap ()
Returns a map of the query parameters.
String getRequestMethod ()
Returns the request method.
Map< String, List< String > > getHeaders ()
Returns a map of the request headers.
Map< String, String > getCookies ()
Returns a map of the request cookies.
Detailed Description
This interface represents the information about an HTTP request context.
Definition at line 9 of file IHttpRequestContextInfo.java.
Member Function Documentation
getCookies()
Map< String, String > IHttpRequestContextInfo.getCookies ()
Returns a map of the request cookies.
Returns
A map of the request cookies.
Implemented in HttpRequestContextInfo.
getHeaders()
Map< String, List< String > > IHttpRequestContextInfo.getHeaders ()
Returns a map of the request headers.
Returns
A map of the request headers.
Implemented in HttpRequestContextInfo.
getHttpExchange()
HttpExchange IHttpRequestContextInfo.getHttpExchange ()
Returns the HttpExchange object associated with the request.
Returns
The HttpExchange object.
Implemented in HttpRequestContextInfo.
getQueryMap()
Map< String, String > IHttpRequestContextInfo.getQueryMap ()
Returns a map of the query parameters.
Returns
A map of the query parameters.
Implemented in HttpRequestContextInfo.
Referenced by EchoHandler.handleGetRequest().
getQueryString()
String IHttpRequestContextInfo.getQueryString ()
Returns the query string of the URI.
Returns
The query string of the URI.
Implemented in HttpRequestContextInfo.
getRequestMethod()
String IHttpRequestContextInfo.getRequestMethod ()
Returns the request method.
Returns
The request method.
Implemented in HttpRequestContextInfo.
getUri()
String IHttpRequestContextInfo.getUri ()
Returns the URI of the request.
Returns
The URI of the request.
Implemented in HttpRequestContextInfo.
Referenced by EchoHandler.handleGetRequest().
getUriPath()
String IHttpRequestContextInfo.getUriPath ()
Returns the path component of the URI.
Returns
The path component of the URI.
Implemented in HttpRequestContextInfo.
Referenced by EchoHandler.handleGetRequest().
The documentation for this interface was generated from the following file:
IHttpRequestContextInfo.java