IAppLoggingStream Interface Reference
The IAppLoggingStream interface defines methods for logging messages and objects.
Public Member Functions
void log (String message)
The log function is used to print a message to the console.
void log (Object object)
The log function is used to print an object to the console.
void log (String[] messages)
The log function takes an array of strings as input and logs each string.
void log (String message, Throwable throwable)
The log function logs a message and an associated throwable object.
void log (Throwable throwable)
The log function is used to log an exception or error.
void flush ()
The flush() function is used to clear any buffered output and write it to the output stream.
Detailed Description
The IAppLoggingStream interface defines methods for logging messages and objects.
Definition at line 6 of file IAppLoggingStream.java.
Member Function Documentation
flush()
void IAppLoggingStream.flush ()
The flush() function is used to clear any buffered output and write it to the output stream.
Implemented in AppLoggingAgent, and AppLoggingStream.
Referenced by AppLoggingAgent.flush().
log() [1/5]
void IAppLoggingStream.log (Object object)
The log function is used to print an object to the console.
Parameters
object The parameter "object" is of type Object, which means it can hold any type of object. It is used to pass an object that you want to log or display.
Implemented in AppLoggingAgent, and AppLoggingStream.
log() [2/5]
void IAppLoggingStream.log (String message)
The log function is used to print a message to the console.
Parameters
message The parameter "message" is of type String, which means it can hold a sequence of characters. It is used to pass a message that you want to log or display.
Implemented in AppLoggingAgent, and AppLoggingStream.
Referenced by AppLoggingAgent.log(), AppLoggingAgent.log(), AppLoggingAgent.log(), AppLoggingAgent.log(), and AppLoggingAgent.log().
log() [3/5]
void IAppLoggingStream.log (String message, Throwable throwable)
The log function logs a message and an associated throwable object.
Parameters
message A string that represents the log message to be logged. This can be any information or description that you want to include in the log.
throwable The "throwable" parameter is used to pass an exception or error object. It allows you to log an error message along with the stack trace of the exception.
Implemented in AppLoggingAgent, and AppLoggingStream.
log() [4/5]
void IAppLoggingStream.log (String[] messages)
The log function takes an array of strings as input and logs each string.
Parameters
messages An array of strings that represents the messages to be logged.
Implemented in AppLoggingAgent, and AppLoggingStream.
log() [5/5]
void IAppLoggingStream.log (Throwable throwable)
The log function is used to log an exception or error.
Parameters
throwable The "throwable" parameter is of type Throwable, which is the base class for all exceptions and errors in Java. It represents an object that can be thrown and caught to handle exceptional conditions in a program.
Implemented in AppLoggingAgent, and AppLoggingStream.
The documentation for this interface was generated from the following file:
IAppLoggingStream.java