IDTO Interface Reference
The IDTO interface represents a Data Transfer Object (DTO) in the shopping system.
Public Member Functions
String getDtoName ()
Returns the name of the DTO (Data Transfer Object).
String getLoadSql (String schema)
Gets the SQL statement for loading data from the database.
String getSaveSql (String schema)
Gets the SQL statement for saving data to the database.
Map< String, DTOTypes > getFields ()
Returns a map of fields in the DTO object.
Object getValue (String fieldName)
Retrieves the value of a field specified by the given field name.
Boolean setValue (String fieldName, Object value)
Sets the value of a field in the DTO.
IDbResultProcessor getLoadProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
IDbResultProcessor getSaveProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
IDTOHome getDtoHome ()
This interface represents the home for IDTO objects.
Detailed Description
The IDTO interface represents a Data Transfer Object (DTO) in the shopping system.
It defines methods for retrieving SQL statements and result processors for loading and saving data.
Definition at line 9 of file IDTO.java.
Member Function Documentation
getDtoHome()
IDTOHome IDTO.getDtoHome ()
This interface represents the home for IDTO objects.
It provides methods to interact with IDTO objects.
Implemented in AuditTrailDTO, CartDTO, CartItemDTO, OrderDTO, OrderItemDTO, PaymentProfileDTO, ProductDTO, PurchaseDTO, RoleDTO, UserDTO, UserProfileDTO, and UserRoleDTO.
getDtoName()
String IDTO.getDtoName ()
Returns the name of the DTO (Data Transfer Object).
Returns
the name of the DTO
Implemented in BaseDTO.
Referenced by BaseDTOHome.buildInsertSql(), BaseDTOHome.buildUpdateSql(), and BaseDTOHome.getLoadSql().
getFields()
Map< String, DTOTypes > IDTO.getFields ()
Returns a map of fields in the DTO object.
Returns
a map containing the fields of the DTO object
Implemented in BaseDTO.
Referenced by BaseDTOHome.buildInsertSql(), BaseDTOHome.buildUpdateSql(), and BaseDTOHome.getLoadSql().
getLoadProcessor()
IDbResultProcessor IDTO.getLoadProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
Returns
the IDbResultProcessor associated with this IDTO
Implemented in BaseDTO.
getLoadSql()
String IDTO.getLoadSql (String schema)
Gets the SQL statement for loading data from the database.
Returns
The SQL statement for loading data.
Implemented in BaseDTO.
getSaveProcessor()
IDbResultProcessor IDTO.getSaveProcessor ()
Returns the IDbResultProcessor associated with this IDTO.
Returns
the IDbResultProcessor associated with this IDTO
Implemented in BaseDTO.
getSaveSql()
String IDTO.getSaveSql (String schema)
Gets the SQL statement for saving data to the database.
Returns
The SQL statement for saving data.
Implemented in BaseDTO.
getValue()
Object IDTO.getValue (String fieldName)
Retrieves the value of a field specified by the given field name.
Parameters
fieldName the name of the field
Returns
the value of the field
Implemented in BaseDTO.
Referenced by BaseDTOHome.buildInsertSql(), BaseDTOHome.buildUpdateSql(), BaseDTOHome.getLoadSql(), and BaseDTOHome.getSaveSql().
setValue()
Boolean IDTO.setValue (String fieldName, Object value)
Sets the value of a field in the DTO.
Parameters
fieldName the name of the field
value the value to be set
Returns
true if the value was successfully set, false otherwise
Implemented in BaseDTO.
The documentation for this interface was generated from the following file:
IDTO.java